---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # RDS Template using snapshot
  * For AWS CloudFormation - RDS Template
  * This template is used when you want to create db using snapshot

  ## DB Engine
  * Postgres

  ## DB Information
  * Master User : kkkkk
  * Default Password : kkkkkk
  * Default DatabaseName : postgres


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "RDS Configuration"
        Parameters:
          - DBName
          - DBInstanceClass

      - 
        Label:
          default: "Snapshot & Read Replica Configuration"
        Parameters:          
          - DBSnapshotArn
      #    - SourceDBInstanceIdentifierParam
      #    - SourceRegionParam

      - 
        Label:
          default: "Storage Configuration"
        Parameters:
          - StorageType
          - StorageSize
          #- IopsParam
          - MaxAllocatedStorageSize
#sanpshot          - KmsKeyParam

      - 
        Label:
          default: "Database Configuration"
        Parameters:
          - DBEngine
#snapshot          - DBEngineVersion
        #  - LicenseModel
#snapshot          - DatabaseNameParam
#snapshot          - MasterUsernameParam
#snapshot          - MasterUserPasswordParam
          - PortNumber
          - ParameterGroupName
        #  - TimezoneParam
        #  - CharacterSetNameParam
          - CACertificateId

      - 
        Label:
          default: "Network Configuration"
        Parameters:
          - PublicAccessible
          - SubnetGroupName
          - AZ
          - SecurityGroupList

      - 
        Label:
          default: "Availability Configuration"
        Parameters:
          - MultiAZ

      - 
        Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriod
          - PreferredBackupWindow

      - 
        Label:
          default: "Log & Monitoring & Maintenance Configuration"
        Parameters:
          - EnableCloudwatchLogs
          - MonitoringIntervalParam
          - MonitoringRoleArnParam
          - PreferredMaintenanceWindow

    #ParameterLabels:
    #  DBName: 
    #    default: "Which VPC should this be deployed to?"


Mappings:
  DBEngineMap:
    postgres:
      Log:
        - postgresql
        - upgrade


Parameters:
  DBName:
    Description: 'RDS Identifier Name'
    Type: String
    AllowedPattern: "^(\\w|-)+$"
    Default: 'rds-y2-test'
  DBInstanceClass:
    Description: 'DB Instance Class'
    Type: String
    Default: db.t3.medium
    AllowedValues: 
      - db.t3.small
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
  DBEngine:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - postgres
    Default: postgres


  DBSnapshotArn:
    Description: 'Snapshot ARN. Create db using Snapshot'
    Type: String
    AllowedPattern: "^(arn:aws:rds:)(\\w|-|:)+$"
    Default: 'arn:aws:rds:ap-'

  PortNumber:
    Description: 'Database Port Number'
    Type: String
    AllowedPattern: "^(\\d)+$"
    Default: '15432'
  ParameterGroupName:
    Description: 'Parameter Group Name'
    Type: String
    AllowedPattern: "^(\\w|-)+$"
  CACertificateId:
    Description: 'CA Certification'
    Type: String


  # Network
  PublicAccessible:
    Description: 'Can publicly access db? (ex> true,false)'
    Type: String
    Default: false
    AllowedValues:
      - false
  SubnetGroupName:
    Description: 'Subnet Group Name'
    Type: String
    AllowedPattern: "^(\\w|-)+$"
    Default: 'db-subnetgroup' #'sg-cluster-y2-test'
  AZ:
    Description: 'Availability Zone / If you check Multi AZ true, this changes to AWS::NoValue'
    Type: AWS::EC2::AvailabilityZone::Name
  SecurityGroupList:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  StorageType:
    Description: 'Storage Type: Only gp2 type'
    Type: String
    Default: 'gp2'
    AllowedValues:
      - gp2
  StorageSize:
    Description: 'Storage Size: 20 ~ 65536 (GiB) '
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 65536
#  IopsParam:
#    Description: 'IOPS'
#    Type: Number
#    Default: 3000
#    MinValue: 1000
#    MaxValue: 80000
  MaxAllocatedStorageSize:
    Description: 'Does DB server increase storage (MinValue: 101GiB / MaxValue: 65536GiB)'
    Type: Number
    Default: 0
    MaxValue: 65536
#snapshot  KmsKeyParam:
#    Description: "KMS Key ID  / null == No encryption"
#    Type: String
#    Default: ""


  # Availability
  MultiAZ:
    Description: 'Does RDS create multi az? (ex> true,false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

            
  # Backup
  BackupRetentionPeriod:
    Description: 'Backup Retention Period: 0 ~ 35 (Day) / 0 == Not use backup'
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 35
  PreferredBackupWindow:
    Description: 'Backup Window(UTC): hh24:mi-hh24:mi (ex> 00:30-01:30) / Input value, when BackupRetentionPeriod is not 0'
    Type: String


  # Log & Monitoring & Maintenance Configuration
  EnableCloudwatchLogs:
    Description: 'Does db use CloudWatch Logs? (ex> true/false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  MonitoringIntervalParam:
    Description: 'Monitoring Interval: 0, 1, 5, 10, 15, 30, 60 (Second) / 0 == Not use monitoring'
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
      - 5
      - 10
      - 15
      - 30
      - 60
  MonitoringRoleArnParam:
    Description: 'Monitoring Role ARN / Input value, when MonitoringIntervalParam is not 0'
    Type: String
  PreferredMaintenanceWindow:
    Description: 'Maintenance Setting(UTC): ddd:hh24:mi-ddd:hh24:mi (ex> wed:07:30-wed:08:00)'
    Type: String
    Default: 'sun:01:00-sun:01:30'


#Rules:


Conditions:
  IncreasesStroage: !Not [!Equals [!Ref MaxAllocatedStorageSize, 0]]
#snapshot  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, '']]
  IsMultiAz: !Equals [!Ref MultiAZ, true]
  SupportsSSLTLS: !Not [!Equals [!Ref CACertificateId, '']]
  SupportsBackup: !Not [!Equals [!Ref BackupRetentionPeriod, 0]]
  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]
  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogs, true]


Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DB Instance
      DBInstanceIdentifier: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass      
      Engine: !Ref DBEngine
#TEST      EngineVersion: !Ref DBEngineVersion
      #LicenseModel: !Ref LicenseModelParam

#snapshot      DBName: !Ref DatabaseNameParam
#snapshot      MasterUsername: !Ref MasterUsernameParam
#snapshot      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortNumber
#TEST      DBParameterGroupName: !Ref ParameterGroupName
      CACertificateIdentifier: !If [SupportsSSLTLS, !Ref CACertificateId, !Ref AWS::NoValue]

      #EnableIAMDatabaseAuthentication: String
      #AssociatedRoles: 
      #  - DBInstanceRole
 

      # Snapshot & Read Replica
      DBSnapshotIdentifier: !Ref DBSnapshotArn
      #SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifierParam
      #SourceRegion: !Ref SourceRegionParam


      # Storage
      StorageType: !Ref StorageType
      AllocatedStorage: !Ref StorageSize
      MaxAllocatedStorage: !If [IncreasesStroage, !Ref MaxAllocatedStorageSize, !Ref AWS::NoValue]
      #Iops: !If [IsAurora, !Ref AWS::NoValue, !Ref IopsParam] 
#snapshot      StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
#snapshot      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PublicAccessible
      DBSubnetGroupName: !Ref SubnetGroupName
      AvailabilityZone: !If [IsMultiAz, !Ref AWS::NoValue, !Ref AZ]
      VPCSecurityGroups: !Ref SecurityGroupList


      # Availability
      MultiAZ: !If [IsMultiAz, true, false]
      
     
      # Backup
#snapshot      DeleteAutomatedBackups: true
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      PreferredBackupWindow: !If [SupportsBackup, !Ref PreferredBackupWindow, !Ref AWS::NoValue]
      CopyTagsToSnapshot: !If [SupportsBackup, true, !Ref AWS::NoValue]


      # Log & Monitoring & Maintenance
      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref DBEngine, Log], !Ref AWS::NoValue]
      MonitoringInterval: !If [UsesMonitoring, !Ref MonitoringIntervalParam, !Ref AWS::NoValue]
      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
#snapshot      EnablePerformanceInsights: false
      #PerformanceInsightsKMSKeyId: String
      #PerformanceInsightsRetentionPeriod: Number


      # Option
#TEST      DeletionProtection: true
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false

      #Domain: String
      #DomainIAMRoleName: String
   
      #UseDefaultProcessorFeatures: String   
      #ProcessorFeatures: 
      #  - ProcessorFeature

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBName

...


