---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Auror Template
  * For AWS CloudFormation - Aurora Template

  ## Resources
  1. 
  2. DB Storage Type
    * Only gp2
  3. 
  4. 

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Aurora Configuration"
        Parameters:
          - DBClusterIdentifierParam
          - DBInstanceClassParam
          - EngineParam
          - EngineVersionParam
      - Label:
          default: "Snapshot & Read Replica Configuration"
        Parameters:          
          - SnapshotIdentifierParam
          - SourceDBClusterIdentifierParam
          - SourceRegionParam
      - Label:
          default: "Database Configuration"
        Parameters:
          - StorageTypeParam
          - StorageSizeParam
          - IopsParam
          - KmsKeyParam
      - Label:
          default: "Database Configuration"
        Parameters:
          - DatabaseNameParam
          - MasterUsernameParam
          - MasterUserPasswordParam
          - PortParam
          - ParameterGroupNameParam
          - OptionGroupNameParam
      - Label:
          default: "Network Configuration"
        Parameters:
          - PubliclyAccessibleParam
          - SubnetGroupNameParam
          - AzParam
          - SecurityGroupListParamSubnetGroupNameParam
      - Label:
          default: "Availability Configuration"
        Parameters:
          - MultiAzParam
          - PromotionTierParam
      - Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriodParam
          - PreferredBackupWindowParam
      - Label:
          default: "Log & Monitoring Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
          - MonitoringIntervalParam
          - MonitoringRoleArnParam


      - Label:
          default: "Subnet Group Configuration"
        Parameters:
          - SubnetGroupSubnetIdsParam


      - Label:
          default: "Parameter Group Configuration"
        Parameters:
          - ParameterGroupFamilyParam


      - Label:
          default: "Option Group Configuration"
        Parameters:
          - OptionEngineVersionParam


Mappings:
  DBEngineMap:
    aurora:
      Log:
        - audit
        - error
        - general
        - slowquery    
    aurora-mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-postgresql:
      Log:
        - postgresql



Parameters:
  DBClusterIdentifierParam:
    Description: 'Aurora Identifier Name'
    Type: String
    Default: 'rds-y2-test'
  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - aurora
      - aurora-mysql
      - aurora-postgresql
  EngineVersionParam:
    Description: 'DB Engine Version'
    Type: String
  
  SnapshotIdentifierParam:
    Description: 'Snapshot ID. Create db using Snapshot'
    Type: String
    Default: 'null'
  SourceDBClusterIdentifierParam:
    Description: 'Source DB Cluster ID, Create Replica'
    Type: String
    Default: 'null'
  SourceRegionParam:
    Description: 'Source DB Region, Create Replica'
    Type: String
    Default: 'null'
    AllowedValues:
      - 'null'
      - 'us-west-1'
      - 'us-east-1'
      - 'ap-northeast-2'

  DatabaseNameParam:
    Description: 'Database Name'
    Type: String
    Default: 'database12'
  MasterUsernameParam:
    Description: 'Master Username'
    Type: String
    Default: 'test12'
  MasterUserPasswordParam:
    Description: 'Master User Password'
    Type: String
    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '5432'
  ParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: 'pg-y2-test'
  OptionGroupNameParam:
    Description: 'Option Group Name'
    Type: String
    Default: 'og-y2-test'

  PubliclyAccessibleParam:
    Description: 'Publicly Accessible'
    Type: String
    Default: false
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-y2-test'
  AzParam:
    Description: 'Availability Zone'
    Type: AWS::EC2::AvailabilityZone::Name
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  StorageTypeParam:
    Description: 'Storage Type'
    Type: String
    Default: 'gp2'
    AllowedValues:
      - gp2
  StorageSizeParam:
    Description: 'Storage Size'
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 65536
  IopsParam:
    Description: 'IOPS'
    Type: Number
    Default: 3000
    MinValue: 1000
    MaxValue: 80000
  KmsKeyParam:
    Description: "KMS Key ID"
    Type: String
    Default: "null"

  # Availability
  MultiAzParam:
    Description: 'Create Multi AZ DB (true,false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  PromotionTierParam:
    Description: 'Promotion Tier(1 > 15) / For Aurora DB'
    Type: Number
    Default: 1
            
  # Backup
  BackupRetentionPeriodParam:
    Description: 'Backup RetenDBOptionGroup'
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 35
  PreferredBackupWindowParam:
    Description: 'Backup Window (hh24:mi-hh24:mi)'
    Type: String
    Default: 'null'

  # Log
  #EnableCloudwatchLogsExportParam:
  #  Description: 'Log List'
  #  Type: 
  #  Default:
  MonitoringIntervalParam:
    Description: 'Monitoring Interval'
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
      - 5
      - 10
      - 15
      - 30
      - 60
  MonitoringRoleArnParam:
    Description: 'Monitoring Role ARN'
    Type: String
    Default: 'null'


  SubnetGroupSubnetIdsParam:
    Description: "Subnet ID"
    Type: List<AWS::EC2::Subnet::Id>


  ParameterGroupFamilyParam:
    Description: 'Parameter Group Family'
    Type: String
    AllowedValues:
      - aurora-mysql5.7
      - aurora-mysql8.0
      - aurora-postgresql11
      - aurora-postgresql12
      - aurora-postgresql13
      - mysql5.7
      - mysql8.0
      - oracle-ee-19
      - oracle-ee-cdb-19
      - oracle-se2-19
      - oracle-se2-cdb-19
      - postgres11
      - postgres12
      - postgres13
      - postgres14
      - sqlserver-ee-13.0
      - sqlserver-se-13.0
      - sqlserver-ex-13.0
      - sqlserver-web-13.0

  OptionEngineVersionParam:
    Description: 'Option Engine Version'
    Type: String
    Default: '8.0'



#Rules:


Conditions:
  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
  IsMultiAz: !Equals [!Ref MultiAzParam, true]

  UsesSnapshot: !Not [!Equals [!Ref SnapshotIdentifierParam, 'null']]
  CreatesReadReplica: !Not [!Equals [!Ref SourceDBClusterIdentifierParam, 'null']]

  UsesBackup: !Not [!Equals [!Ref BackupRetentionPeriodParam, 0]]
  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]


Resources:
  RDSInstance:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - DBSubnetGroup
      - DBParameterGroup
      - DBOptionGroup
    Properties:
      # DB Instance
      Engine: !Ref EngineParam
      EngineMode: 'provisioned'
      EngineVersion: !Ref EngineVersionParam
      
      #GlobalClusterIdentifier: String
      DBClusterIdentifier: !Ref DBClusterIdentifierParam

      DatabaseName: !Ref DatabaseNameParam
      MasterUsername: !Ref MasterUsernameParam
      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam

      DBClusterParameterGroupName: !Ref DBParameterGroup
      OptionGroupName: !Ref DBOptionGroup

      #LicenseModel: String
      #EnableIAMDatabaseAuthentication: String

      SnapshotIdentifier: !If [UsesSnapshot, !Ref SnapshotIdentifierParam, !Ref AWS::NoValue]
      SourceDBClusterIdentifier: !If [CreatesReadReplica, !Ref SourceDBClusterIdentifierParam, !Ref AWS::NoValue]
      SourceRegion: !If [CreatesReadReplica, !Ref SourceRegionParam, !Ref AWS::NoValue]


      # Storage
      StorageType: !Ref StorageTypeParam
      AllocatedStorage: !Ref StorageSizeParam
      StorageEncrypted: !If [IsEncrypted, true, false]
      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PubliclyAccessibleParam
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      AvailabilityZone: !Ref AzParam
      VpcSecurityGroupIds: !Ref SecurityGroupListParam


      # Availability
      MultiAZ: !If [IsMultiAz, true, false]
      PromotionTier: !If [IsMultiAz, !Ref PromotionTierParam, !Ref AWS::NoValue]
      
     
      # Backup
      DeleteAutomatedBackups: true
      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
      PreferredBackupWindow: !If [UsesBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
      CopyTagsToSnapshot: false


      # Log & Monitoring
      EnableCloudwatchLogsExports: !FindInMap [DBEngineMap, !Ref EngineParam, Log]
      MonitoringInterval: !Ref MonitoringIntervalParam
      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]

      EnablePerformanceInsights: false
      #PerformanceInsightsKMSKeyId: String
      #PerformanceInsightsRetentionPeriod: Number



      # Option
      DeletionProtection: true

      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false

      #PreferredMaintenanceWindow: String      

      #AssociatedRoles: 
      #  - DBInstanceRole

      # EnableHttpEndpoint: Boolean

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBClusterIdentifierParam


  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: !Sub 'Subnet Group for ${SubnetGroupNameParam}'
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      SubnetIds: !Ref SubnetGroupSubnetIdsParam
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref SubnetGroupNameParam

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: !Sub 'Parameter Group for ${ParameterGroupNameParam}'
      Family: !Ref ParameterGroupFamilyParam
      #Parameters: 
      #  Key : Value
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref ParameterGroupNameParam

  DBOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties: 
      EngineName: !Ref EngineParam
      MajorEngineVersion: !Ref OptionEngineVersionParam
      #OptionConfigurations: 
      #  - OptionConfiguration
      OptionGroupDescription: !Sub 'Option Group for ${OptionGroupNameParam}'
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref OptionGroupNameParam



Outputs:
  InstanceId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...


