---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Aurora Cluster Template
  * For AWS CloudFormation - Aurora Cluster Template

  ## Resources
  1. 
  2. DB Storage Type
    * Only gp2
  3. 
  4. 

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Aurora Cluster Configuration"
        Parameters:
          - DBClusterIdentifierParam
          - DBInstanceClassParam
          - EngineParam
          - EngineVersionParam
      - Label:
          default: "Snapshot & Read Replica Configuration"
        Parameters:
          - RestoreTypeParam
          - SnapshotIdentifierParam
          - SourceDBClusterIdentifierParam
          - SourceRegionParam
      - Label:
          default: "Storage Configuration"
        Parameters:
          - KmsKeyParam
      - Label:
          default: "Database Configuration"
        Parameters:
          - DatabaseNameParam
          - MasterUsernameParam
          - MasterUserPasswordParam
          - PortParam
          - ClusterParameterGroupNameParam
      - Label:
          default: "Network Configuration"
        Parameters:
          - PubliclyAccessibleParam
          - SubnetGroupNameParam
          - AzParam
          - SecurityGroupListParam
      - Label:
          default: "Availability Configuration"
        Parameters:
          - PromotionTierParam
      - Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriodParam
          - PreferredBackupWindowParam
      - Label:
          default: "Log & Monitoring Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
          - MonitoringIntervalParam
          - MonitoringRoleArnParam


      - Label:
          default: "Subnet Group Configuration"
        Parameters:
          - SubnetGroupSubnetIdsParam


      - Label:
          default: "Parameter Group Configuration"
        Parameters:
          - ClusterParameterGroupFamilyParam


      - Label:
          default: "Option Group Configuration"
        Parameters:
          - OptionEngineVersionParam


Mappings:
  DBEngineMap:
    aurora:
      Log:
        - audit
        - error
        - general
        - slowquery    
    aurora-mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-postgresql:
      Log:
        - postgresql



Parameters:
  DBClusterIdentifierParam:
    Description: 'Aurora Identifier Name'
    Type: String
    Default: 'rds-y2-test'
  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - aurora
      - aurora-mysql
      - aurora-postgresql
  EngineVersionParam:
    Description: 'DB Engine Version'
    Type: String
  

  RestoreTypeParam:
     Description: 'Source DB Region, Create Replica'
    Type: String
    Default: 'null'
    AllowedValues:
      - full-copy
      - copy-on-write
      - 'null'
  SnapshotIdentifierParam:
    Description: 'Snapshot ID. Create db using Snapshot'
    Type: String
    Default: 'null'
  SourceDBClusterIdentifierParam:
    Description: 'Source DB Cluster ID, Create Replica'
    Type: String
    Default: 'null'
  SourceRegionParam:
    Description: 'Source DB Region, Create Replica'
    Type: String
    Default: 'null'
    AllowedValues:
      - 'null'
      - 'us-west-1'
      - 'us-east-1'
      - 'ap-northeast-2'

  DatabaseNameParam:
    Description: 'Database Name'
    Type: String
    Default: 'database12'
  MasterUsernameParam:
    Description: 'Master Username'
    Type: String
    Default: 'test12'
  MasterUserPasswordParam:
    Description: 'Master User Password'
    Type: String
    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '5432'
  ClusterParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: 'pg-y2-test'


  # Network
  PubliclyAccessibleParam:
    Description: 'Publicly Accessible'
    Type: String
    Default: false
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-y2-test'
  AzParam:
    Description: 'Availability Zone'
    Type: AWS::EC2::AvailabilityZone::Name
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  KmsKeyParam:
    Description: "KMS Key ID"
    Type: String
    Default: "null"

  # Availability
 PromotionTierParam:
    Description: 'Promotion Tier(1 > 15) / For Aurora DB'
    Type: Number
    Default: 1
            
  # Backup
  BackupRetentionPeriodParam:
    Description: 'Backup Retention Period'
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 35
  PreferredBackupWindowParam:
    Description: 'Backup Window (hh24:mi-hh24:mi)'
    Type: String
    Default: 'null'

  # Log
  #EnableCloudwatchLogsExportParam:
  #  Description: 'Log List'
  #  Type: 
  #  Default:
  MonitoringIntervalParam:
    Description: 'Monitoring Interval'
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
      - 5
      - 10
      - 15
      - 30
      - 60
  MonitoringRoleArnParam:
    Description: 'Monitoring Role ARN'
    Type: String
    Default: 'null'


  SubnetGroupSubnetIdsParam:
    Description: "Subnet ID"
    Type: List<AWS::EC2::Subnet::Id>


  ClusterParameterGroupFamilyParam:
    Description: 'Parameter Group Family'
    Type: String
    AllowedValues:
      - aurora-mysql5.7
      - aurora-mysql8.0
      - aurora-postgresql11
      - aurora-postgresql12
      - aurora-postgresql13


  OptionEngineVersionParam:
    Description: 'Option Engine Version'
    Type: String
    Default: '8.0'



#Rules:


Conditions:
  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
 
  UsesRestore: !Not [!Equals [!Ref RestoreTypeParamm 'null']]
  UsesSnapshot: !Not [!Equals [!Ref SnapshotIdentifierParam, 'null']]
  CreatesReadReplica: !Not [!Equals [!Ref SourceDBClusterIdentifierParam, 'null']]

  UsesBackup: !Not [!Equals [!Ref BackupRetentionPeriodParam, 0]]
  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]


Resources:
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      # DB Instance
      Engine: !Ref EngineParam
      EngineMode: 'provisioned'
      EngineVersion: !Ref EngineVersionParam
      
      #GlobalClusterIdentifier: String
      DBClusterIdentifier: !Ref DBClusterIdentifierParam

      DatabaseName: !Ref DatabaseNameParam
      MasterUsername: !Ref MasterUsernameParam
      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam

      DBClusterParameterGroupName: !Ref DBParameterGroup

      #EnableIAMDatabaseAuthentication: String
      RestoreType: !If [UsesRestore, !Ref RestoreTypeParam, !Ref AWS::NoValue]
      #SnapshotIdentifier: !If [UsesSnapshot, !Ref SnapshotIdentifierParam, !Ref AWS::NoValue]
      #SourceDBClusterIdentifier: !If [CreatesReadReplica, !Ref SourceDBClusterIdentifierParam, !Ref AWS::NoValue]
      #SourceRegion: !If [CreatesReadReplica, !Ref SourceRegionParam, !Ref AWS::NoValue]


      # Storage
      StorageEncrypted: !If [IsEncrypted, true, false]
      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      VpcSecurityGroupIds: !Ref SecurityGroupListParam
    
     
      # Backup
      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
      PreferredBackupWindow: !If [UsesBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
      CopyTagsToSnapshot: false


      # Log & Monitoring
      EnableCloudwatchLogsExports: !FindInMap [DBEngineMap, !Ref EngineParam, Log]


      # Option
      DeletionProtection: true

      #PreferredMaintenanceWindow: String      
      #AssociatedRoles: 
      #  - DBInstanceRole
      # EnableHttpEndpoint: Boolean
      #BacktrackWindow: 0

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBClusterIdentifierParam



  RDSInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - DBSubnetGroup
      - DBParameterGroup
    Properties:
      # DB Instance
      Engine: !Ref EngineParam
      
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !Ref DBInstanceClassParam
      DBParameterGroupName: !Ref DBParameterGroup


      #LicenseModel: String
      DBSnapshotIdentifier: !If [UsesSnapshot, !Ref DBSnapshotIdentifierParam, !Ref AWS::NoValue]
      SourceDBInstanceIdentifier: !If [CreatesReadReplica, !Ref SourceDBInstanceIdentifierParam, !Ref AWS::NoValue]
      SourceRegion: !If [CreatesReadReplica, !Ref SourceRegionParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PubliclyAccessibleParam
      AvailabilityZone: !Ref AzParam

      # Availability
      PromotionTier: !Ref PromotionTierParam
     
      # Backup
      DeleteAutomatedBackups: true

      # Log & Monitoring
      MonitoringInterval: !Ref MonitoringIntervalParam
      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]

      EnablePerformanceInsights: false
      #PerformanceInsightsKMSKeyId: String
      #PerformanceInsightsRetentionPeriod: Number

      # Option
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false

      #PreferredMaintenanceWindow: String      

      #Timezone: String

      #AssociatedRoles: 
      #  - DBInstanceRole
 
      #CACertificateIdentifier: String

      #Domain: String
      #DomainIAMRoleName: String
   
      #UseDefaultProcessorFeatures: String   
      #ProcessorFeatures: 
      #  - ProcessorFeature

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBIdentifierNameParam


  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: !Sub 'Subnet Group for ${SubnetGroupNameParam}'
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      SubnetIds: !Ref SubnetGroupSubnetIdsParam
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref SubnetGroupNameParam

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties: 
      Description: !Sub 'Cluster Parameter Group for ${ClusterParameterGroupNameParam}'
      Family: !Ref ClusterParameterGroupFamilyParam
      #Parameters:
      #  time_zone: US/Eastern
      #  character_set_database: utf32
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref ClusterParameterGroupNameParam



Outputs:
  InstanceId:
    Description: Cluster ID
    Value: !Ref AuroraCluster
    Export:
      Name: !Sub "${AWS::StackName}-ClusterId"
...


