---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # RDS Template
  * For AWS CloudFormation - RDS Template

  ## Resources
  1. 
  2. DB Storage Type
    * Only gp2
  3. 
  4. 

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "RDS Configuration"
        Parameters:
          - DBIdentifierNameParam
          - DBInstanceClassParam
          - EngineParam
#replica          - EngineVersionParam
      - Label:
          default: "Snapshot & Read Replica Configuration"
        Parameters:          
#          - DBSnapshotIdentifierParam
          - SourceDBInstanceIdentifierParam
          - SourceRegionParam
      - Label:
          default: "Database Configuration"
        Parameters:
          - StorageTypeParam
#replica          - StorageSizeParam
#          - IopsParam
          - KmsKeyParam
      - Label:
          default: "Database Configuration"
        Parameters:
#replica          - DatabaseNameParam
#replica          - MasterUsernameParam
#replica          - MasterUserPasswordParam
          - PortParam
#replica          - ParameterGroupNameParam
#replica          - OptionGroupNameParam
      - Label:
          default: "Network Configuration"
        Parameters:
          - PubliclyAccessibleParam
          - SubnetGroupNameParam
          - AzParam
          - SecurityGroupListParamSubnetGroupNameParam
#replica      - Label:
#replica          default: "Availability Configuration"
#replica        Parameters:
#repclia          - MultiAzParam
#replica      - Label:
#replica          default: "Backup Configuration"
#replica        Parameters:
#replica          - BackupRetentionPeriodParam
#replica          - PreferredBackupWindowParam
      - Label:
          default: "Log & Monitoring Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
          - MonitoringIntervalParam
          - MonitoringRoleArnParam

      - Label:
          default: "Subnet Group Configuration"
        Parameters:
          - SubnetGroupSubnetIdsParam

#replica      - Label:
#          default: "Parameter Group Configuration"
#        Parameters:
#          - ParameterGroupFamilyParam

#replica      - Label:
#          default: "Option Group Configuration"
#        Parameters:
#          - OptionEngineVersionParam

Mappings:
  DBEngineMap:
    mariadb:
      Log:
        - audit
        - error
        - general
        - slowquery
    mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    oracle-ee:
      Log:
        - alert
        - audit
        - listener
        - trace
    oracle-ee-cdb:
      Log: 
        - alert
        - audit
        - listener
        - trace
    oracle-se2:
      Log:
        - alert
        - audit
        - listener
        - trace
    oracle-cdb:
      Log:
        - alert
        - audit
        - listener
        - trace
    postgres:
      Log:
        - postgresql
        - upgrade
    sqlserver-ee:
      Log:
        - agent
        - error
    sqlserver-se:
      Log:
        - agent
        - error
    sqlserver-ex:
      Log:
        - agent
        - error
    sqlserver-web:
      Log:
        - agent
        - error


Parameters:
  DBIdentifierNameParam:
    Description: 'RDS Identifier Name'
    Type: String
    Default: 'rds-y2-test'
  DBInstanceClassParam:
    Description: 'DB Instance Class'
    Type: String
    Default: db.t3.medium
    AllowedValues: 
      - db.t3.small
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - mariadb
      - mysql
      - oracle-ee
      - oracle-ee-cdb
      - oracle-se2
      - oracle-cdb
      - postgres
      - sqlserver-ee
      - sqlserver-se
      - sqlserver-ex
      - sqlserver-web
#replica  EngineVersionParam:
#    Description: 'DB Engine Version'
#    Type: String
  
#  DBSnapshotIdentifierParam:
#    Description: 'Snapshot ID. Create db using Snapshot'
#    Type: String
#    Default: 'null'
  SourceDBInstanceIdentifierParam:
    Description: 'Source DB ID, Create Read Replica'
    Type: String
    Default: 'null'
    AllowedPattern: "^[^(null)]$"
    ConstraintDescription: "Not Null"
  SourceRegionParam:
    Description: 'Source DB Region, Create Read Replica'
    Type: String
    Default: 'null'
    AllowedValues:
      - 'null'
      - 'us-west-1'
      - 'us-east-1'
      - 'ap-northeast-2'

#replica  DatabaseNameParam:
#    Description: 'Database Name'
#    Type: String
#    Default: 'database12'
#replica  MasterUsernameParam:
#    Description: 'Master Username'
#    Type: String
#    Default: 'test12'
#replica  MasterUserPasswordParam:
#    Description: 'Master User Password'
#    Type: String
#    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '5432'
#replica  ParameterGroupNameParam:
#    Description: 'Parameter Group Name'
#    Type: String
#    Default: 'pg-y2-test'
#replica  OptionGroupNameParam:
#    Description: 'Option Group Name'
#    Type: String
#    Default: 'og-y2-test'

  PubliclyAccessibleParam:
    Description: 'Publicly Accessible'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-y2-test'
  AzParam:
    Description: 'Availability Zone: If you want Multi AZ, Select anyting because this chanes to AWS::NoValue'
    Type: String      # replica
    Default: 'null'
    AllowedValues:
      - 'null'
      - 'us-west-1a'
      - 'us-west-1b'      
      - 'us-east-1a'
      - 'us-east-1b'
      - 'ap-northeast-2a'      
      - 'ap-northeast-2c'
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  StorageTypeParam:
    Description: 'Storage Type'
    Type: String
    Default: 'gp2'
    AllowedValues:
      - gp2
#replica  StorageSizeParam:
#    Description: 'Storage Size'
#    Type: Number
#    Default: 20
#    MinValue: 20
#    MaxValue: 65536
#  IopsParam:
#    Description: 'IOPS'
#    Type: Number
#    Default: 3000
#    MinValue: 1000
#    MaxValue: 80000
  KmsKeyParam:
    Description: "KMS Key ID"
    Type: String
    Default: "null"

  # Availability
#replica  MultiAzParam:
#    Description: 'Create Multi AZ DB (true,false)'
#    Type: String
#    Default: false
#    AllowedValues:
#      - true
#      - false

            
  # Backup
#replica  BackupRetentionPeriodParam:
#    Description: 'Backup Retention Period (0 ~ 35)'
#    Type: Number
#    Default: 0
#    MinValue: 0
#    MaxValue: 35
#replica  PreferredBackupWindowParam:
#    Description: 'Backup Window (hh24:mi-hh24:mi)'
#    Type: String
#   Default: 'null'

  # Log
  EnableCloudwatchLogsExportParam:
    Description: 'Log List'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  MonitoringIntervalParam:
    Description: 'Monitoring Interval'
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
      - 5
      - 10
      - 15
      - 30
      - 60
  MonitoringRoleArnParam:
    Description: 'Monitoring Role ARN'
    Type: String
    Default: 'null'


  SubnetGroupSubnetIdsParam:
    Description: "Subnet ID"
    Type: List<AWS::EC2::Subnet::Id>


#replica  ParameterGroupFamilyParam:
#    Description: 'Parameter Group Family'
#   Type: String
#    AllowedValues:
#      - mysql5.7
#      - mysql8.0
#      - oracle-ee-19
#      - oracle-ee-cdb-19
#      - oracle-se2-19
#      - oracle-se2-cdb-19
#      - postgres11
#      - postgres12
#      - postgres13
#      - postgres14
#      - sqlserver-ee-13.0
#      - sqlserver-se-13.0
#      - sqlserver-ex-13.0
#      - sqlserver-web-13.0

#replica  OptionEngineVersionParam:
#    Description: 'Option Engine Version'
#    Type: String
#    Default: '8.0'



#Rules:


Conditions:
  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
#replica  IsMultiAz: !Equals [!Ref MultiAzParam, true]
#replica  IsSqlServer: !Or
#    - !Equals [!Ref EngineParam, 'sqlserver-ee']
#    - !Equals [!Ref EngineParam, 'sqlserver-se']
#    - !Equals [!Ref EngineParam, 'sqlserver-ex']
#    - !Equals [!Ref EngineParam, 'sqlserver-web']
#replica  UsesBackup: !Not [!Equals [!Ref BackupRetentionPeriodParam, 0]]
  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]
  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogsExportParam, true]

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DB Instance
#      Engine: !Ref EngineParam
#      EngineVersion: !Ref EngineVersionParam
      
      DBInstanceIdentifier: !Ref DBIdentifierNameParam
      DBInstanceClass: !Ref DBInstanceClassParam

#replica      DBName: !If [IsSqlServer,!Ref AWS::NoValue,!Ref DatabaseNameParam]
#replica      MasterUsername: !Ref MasterUsernameParam
#replica      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam

#replica      DBParameterGroupName: !Ref DBParameterGroup
#replica      OptionGroupName: !Ref DBOptionGroup

      #LicenseModel: String
      #EnableIAMDatabaseAuthentication: String

      #DBSnapshotIdentifier: !Ref DBSnapshotIdentifierParam
      SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifierParam
      SourceRegion: !Ref SourceRegionParam


      # Storage
      StorageType: !Ref StorageTypeParam
#replica      AllocatedStorage: !Ref StorageSizeParam
      #MaxAllocatedStorage: !If [IsAurora, !Ref AWS::NoValue, Number]
      #Iops: !If [IsAurora, !Ref AWS::NoValue, !Ref IopsParam] 
      StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PubliclyAccessibleParam
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      AvailabilityZone: !Ref AzParam #!If [IsMultiAz, !Ref AWS::NoValue, !Ref AzParam]
      VPCSecurityGroups: !Ref SecurityGroupListParam


      # Availability
#replica      MultiAZ: !If [IsMultiAz, true, false]
      
     
      # Backup
      DeleteAutomatedBackups: true
#replica      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
#replica      PreferredBackupWindow: !If [UsesBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
      CopyTagsToSnapshot: false


      # Log & Monitoring
      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
      MonitoringInterval: !If [UsesMonitoring, !Ref MonitoringIntervalParam, !Ref AWS::NoValue]
      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]
      EnablePerformanceInsights: false
      #PerformanceInsightsKMSKeyId: String
      #PerformanceInsightsRetentionPeriod: Number


      # Option
      DeletionProtection: false 
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false

      #PreferredMaintenanceWindow: String      

      #Timezone: String

      #AssociatedRoles: 
      #  - DBInstanceRole
 
      #CACertificateIdentifier: String
      #CharacterSetName: String

      #Domain: String
      #DomainIAMRoleName: String
   
      #UseDefaultProcessorFeatures: String   
      #ProcessorFeatures: 
      #  - ProcessorFeature

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBIdentifierNameParam


Outputs:
  InstanceId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...


