---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # RDS Template
  * For AWS CloudFormation - RDS Template

  ## Resources
  1. 
  2. 
  3. 
  4. 

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "RDS Configuration"
        Parameters:
          - DBEngineNameParam
          - DBEngineVersionParam
      - Label:
          default: "Subnet Group Configuration"
        Parameters:
          - SubnetGroupNameParam
          - SubnetGroupNameParam
      - Label:
          default: "Parameter Group Configuration"
        Parameters:
          - ParameterGroupFamilyParam
          - ParameterGroupNameParam

      - Label:
          default: "Option Group Configuration"
        Parameters:
          - OptionGroupNameParam
          - 


#Mappings:


Parameters:
  DBEngineNameParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - mariadb
      - mysql
      - oracle-ee
      - oracle-ee-cdb  
      - oracle-se2
      - oracle-cdb
      - postgres
      - sqlserver-ee
      - sqlserver-se
      - sqlserver-ex
      - sqlserver-web
  DBEngineVersionParam:
    Description: 'DB Engine Version'
    Type: String
    AllowedValues:


  SubnetGroupNameParam:
    Description: "Subnet Group Name"
    Type: String
    Default: "null"
  SubnetGroupSubnetIdsParam:
    Description: "Subnet ID"
    Type: List<AWS::EC2::Subnet::Id>

  ParameterGroupFamilyParam:
    Description: 'Parameter Group Family'
    Type: String
    AllowedValues:
      - aurora-mysql5.7
      - aurora-mysql8.0
      - aurora-postgresql11
      - aurora-postgresql12
      - aurora-postgresql13
      - mysql5.7
      - mysql8.0
      - oracle-ee-19
      - oracle-ee-cdb-19
      - oracle-se2-19
      - oracle-se2-cdb-19
      - postgres11
      - postgres12
      - postgres13
      - postgres14
      - sqlserver-ee-13.0
      - sqlserver-se-13.0
      - sqlserver-ex-13.0
      - sqlserver-web-13.0
  ParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: "null"

  OptionGroupNameParam:
    Description: 'Option Group Name'
    Type: String
    Default: "null"



#Rules:


Conditions:
  IsAurora: 

  IsPubSub1: !Not [!Equals [!Select [0, !Ref PubSubAZList], ""]]

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DB Instance
      Engine: String
      EngineVersion: String 
      
      DBInstanceIdentifier: !If [IsAurora, !Ref AWS::NoValue,]
      DBClusterIdentifier: !If [IsAurora, , !Ref AWS::NoValue]
      DBInstanceClass: 

      DBName: String      
      MasterUsername: String
      MasterUserPassword: String
      Port: String


      # Storage
      StorageType: String
      AllocatedStorage: !If [IsAurora, , !Ref AWS::NoValue]
      MaxAllocatedStorage: Integer      
      Iops: Integer
      StorageEncrypted: Boolean
      KmsKeyId: String


      # Network
      AvailabilityZone: String



      AllowMajorVersionUpgrade: Boolean
      AssociatedRoles: 
        - DBInstanceRole
      AutoMinorVersionUpgrade: Boolean
      

      # Backup
      BackupRetentionPeriod: Integer
      DBSnapshotIdentifier: String


      
      # Option


      
      CACertificateIdentifier: String
      CharacterSetName: String
      CopyTagsToSnapshot: Boolean


      DBParameterGroupName: String
      DBSecurityGroups: 
        - String
      
      DBSubnetGroupName: String
      DeleteAutomatedBackups: Boolean
      DeletionProtection: Boolean
      Domain: String
      DomainIAMRoleName: String
      EnableCloudwatchLogsExports: 
        - String
      EnableIAMDatabaseAuthentication: Boolean
      EnablePerformanceInsights: Boolean



      LicenseModel: String


      MonitoringInterval: Integer
      MonitoringRoleArn: String
      MultiAZ: Boolean
      OptionGroupName: String
      PerformanceInsightsKMSKeyId: String
      PerformanceInsightsRetentionPeriod: Integer

      PreferredBackupWindow: String
      PreferredMaintenanceWindow: String
      ProcessorFeatures: 
        - ProcessorFeature
      PromotionTier: Integer
      PubliclyAccessible: Boolean
      SourceDBInstanceIdentifier: String
      SourceRegion: String


      Timezone: String
      UseDefaultProcessorFeatures: Boolean
      VPCSecurityGroups: 
        - String
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref SubnetGroupSubnetIdsParam


  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: !Sub 'Subnet Group for ${SubnetGroupNameParam}'
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      SubnetIds: !Ref SubnetGroupSubnetIdsParam
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref SubnetGroupSubnetIdsParam

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: !Sub 'Subnet Group for ${ParameterGroupNameParam}'
      Family: !Ref ParameterGroupFamilyParam
      #Parameters: 
      #  Key : Value
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref ParameterGroupNameParam

  DBOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties: 
      EngineName: String
      MajorEngineVersion: String
      #OptionConfigurations: 
      #  - OptionConfiguration
      OptionGroupDescription: !Sub 'Subnet Group for ${OptionGroupNameParam}'
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref OptionGroupNameParam



Outputs:
  InstanceId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...


