---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # RDS Snapshot Template
  * For AWS CloudFormation - RDS Snapshot Template
  * Delete Parameters using snapshot parameter
    * CharacterSetName
    * DBClusterIdentifier
    * DBName
    * DeleteAutomatedBackups
    * EnablePerformanceInsights
    * KmsKeyId
    * MasterUsername
    * MonitoringInterval
    * MonitoringRoleArn
    * PerformanceInsightsKMSKeyId
    * PerformanceInsightsRetentionPeriod
    * PromotionTier
    * SourceDBInstanceIdentifier
    * SourceRegion
    * StorageEncrypted
    * Timezone

  ## Resources
  1. 
  2. DB Storage Type
    * Only gp2
  3. 
  4. 

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "RDS Configuration"
        Parameters:
          - DBIdentifierNameParam
          - DBInstanceClassParam
          - EngineParam
          - EngineVersionParam
      - Label:
          default: "Snapshot & Read Replica Configuration"
        Parameters:          
          - DBSnapshotIdentifierParam
#          - SourceDBInstanceIdentifierParam
#          - SourceRegionParam
      - Label:
          default: "Storage Configuration"
        Parameters:
          - StorageTypeParam
#snapshot          - StorageSizeParam
#          - IopsParam
#snapshot          - KmsKeyParam
      - Label:
          default: "Database Configuration"
        Parameters:
#snapshot          - DatabaseNameParam
#snapshot          - MasterUsernameParam
#snapshot          - MasterUserPasswordParam
          - PortParam
          - ParameterGroupNameParam
          - OptionGroupNameParam
      - Label:
          default: "Network Configuration"
        Parameters:
          - PubliclyAccessibleParam
          - SubnetGroupNameParam
          - AzParam
          - SecurityGroupListParam
      - Label:
          default: "Availability Configuration"
        Parameters:
          - MultiAzParam
      - Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriodParam
          - PreferredBackupWindowParam
      - Label:
          default: "Log & Monitoring & Maintenance Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
#snapshot          - MonitoringIntervalParam
#sanpshot          - MonitoringRoleArnParam
          - PreferredMaintenanceWindowParam



Mappings:
  DBEngineMap:
    mariadb:
      Log:
        - audit
        - error
        - general
        - slowquery
    mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    oracle-ee:
      Log:
        - alert
        - audit
        - listener
        - trace
    oracle-ee-cdb:
      Log: 
        - alert
        - audit
        - listener
        - trace
    oracle-se2:
      Log:
        - alert
        - audit
        - listener
        - trace
    oracle-cdb:
      Log:
        - alert
        - audit
        - listener
        - trace
    postgres:
      Log:
        - postgresql
        - upgrade
    sqlserver-ee:
      Log:
        - agent
        - error
    sqlserver-se:
      Log:
        - agent
        - error
    sqlserver-ex:
      Log:
        - agent
        - error
    sqlserver-web:
      Log:
        - agent
        - error


Parameters:
  DBIdentifierNameParam:
    Description: 'RDS Identifier Name'
    Type: String
    Default: 'rds-y2-test-snapshot'
  DBInstanceClassParam:
    Description: 'DB Instance Class'
    Type: String
    Default: db.t3.medium
    AllowedValues: 
      - db.t3.small
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - mariadb
      - mysql
      - oracle-ee
      - oracle-ee-cdb  
      - oracle-se2
      - oracle-cdb
      - postgres
      - sqlserver-ee
      - sqlserver-se
      - sqlserver-ex
      - sqlserver-web
  EngineVersionParam:
    Description: 'DB Engine Version'
    Type: String
  
  DBSnapshotIdentifierParam:
    Description: 'Snapshot ARN. Create db using Snapshot'
    Type: String
    Default: 'null'
#  SourceDBInstanceIdentifierParam:
#    Description: 'Source DB ID, Create Read Replica'
#    Type: String
#    Default: 'null'
#  SourceRegionParam:
#    Description: 'Source DB Region, Create Read Replica'
#    Type: String
#    Default: 'null'
#    AllowedValues:
#      - 'null'
#      - 'us-west-1'
#      - 'us-east-1'
#      - 'ap-northeast-2'

#snapshot  DatabaseNameParam:
#    Description: 'Database Name'
#    Type: String
#    Default: 'null'
#snapshot  MasterUsernameParam:
#    Description: 'Master Username'
#    Type: String
#    Default: 'null'
#snapshot  MasterUserPasswordParam:
#    Description: 'Master User Password'
#    Type: String
#    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '5432'
  ParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: 'pg-y2-test-snapshot'
  OptionGroupNameParam:
    Description: 'Option Group Name'
    Type: String
    Default: 'og-y2-test-snapshot'

  PubliclyAccessibleParam:
    Description: 'Publicly Accessible'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-y2-test'
  AzParam:
    Description: 'Availability Zone: If you want Multi AZ, Select anyting because this chanes to AWS::NoValue'
    Type: AWS::EC2::AvailabilityZone::Name
    Default: 'null'
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  StorageTypeParam:
    Description: 'Storage Type'
    Type: String
    Default: 'gp2'
    AllowedValues:
      - gp2
#replica  StorageSizeParam:
#    Description: 'Storage Size'
#    Type: Number
#    Default: 20
#    MinValue: 20
#    MaxValue: 65536
#  IopsParam:
#    Description: 'IOPS'
#    Type: Number
#    Default: 3000
#    MinValue: 1000
#    MaxValue: 80000
#snapshot  KmsKeyParam:
#    Description: "KMS Key ID"
#    Type: String
#    Default: "null"

  # Availability
  MultiAzParam:
    Description: 'Create Multi AZ DB (true,false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

            
  # Backup
  BackupRetentionPeriodParam:
    Description: 'Backup Retention Period (0 ~ 35)'
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 35
  PreferredBackupWindowParam:
    Description: 'Backup Window (hh24:mi-hh24:mi)'
    Type: String
    Default: 'null'

  # Log
  EnableCloudwatchLogsExportParam:
    Description: 'Log List'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
#snapshot  MonitoringIntervalParam:
#    Description: 'Monitoring Interval'
#    Type: Number
#    Default: 0
#    AllowedValues:
#      - 0
#      - 1
#      - 5
#      - 10
#      - 15
#      - 30
#      - 60
#snapshot  MonitoringRoleArnParam:
#    Description: 'Monitoring Role ARN'
#    Type: String
#    Default: 'null'
  
  # Maintenance
  PreferredMaintenanceWindowParam:
    Description: 'Maintenance : ddd:hh24:mi-ddd:hh24:mi (ex> wed:07:30-wed:08:00)'
    Type: String
    Defulat: 'sun:01:00-sun:01:30'



#Rules:


Conditions:
#  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
  IsMultiAz: !Equals [!Ref MultiAzParam, true]
  IsSqlServer: !Or
    - !Equals [!Ref EngineParam, 'sqlserver-ee']
    - !Equals [!Ref EngineParam, 'sqlserver-se']
    - !Equals [!Ref EngineParam, 'sqlserver-ex']
    - !Equals [!Ref EngineParam, 'sqlserver-web']
  UsesBackup: !Not [!Equals [!Ref BackupRetentionPeriodParam, 0]]
#  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]
  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogsExportParam, true]

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DB Instance
      Engine: !Ref EngineParam
      EngineVersion: !Ref EngineVersionParam
      
      DBInstanceIdentifier: !Ref DBIdentifierNameParam
      DBInstanceClass: !Ref DBInstanceClassParam

#snapshot      DBName: !If [IsSqlServer,!Ref AWS::NoValue,!Ref DatabaseNameParam]
#snapshot      MasterUsername: !Ref MasterUsernameParam
#snapshot      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam
      DBParameterGroupName: !Ref ParameterGroupNameParam
      OptionGroupName: !Ref OptionGroupNameParam


      #LicenseModel: String
      #EnableIAMDatabaseAuthentication: String

      # Snapshot & Read Replica
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifierParam
#snapshot      SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifierParam
#snapshot      SourceRegion: !Ref SourceRegionParam


      # Storage
      StorageType: !Ref StorageTypeParam
#      AllocatedStorage: !Ref StorageSizeParam
#      MaxAllocatedStorage: !If [IsAurora, !Ref AWS::NoValue, Number]
#      Iops: !If [IsAurora, !Ref AWS::NoValue, !Ref IopsParam] 
#snapshot      StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
#snapshot      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PubliclyAccessibleParam
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      AvailabilityZone: !If [IsMultiAz, !Ref AWS::NoValue, !Ref AzParam]
      VPCSecurityGroups: !Ref SecurityGroupListParam


      # Availability
      MultiAZ: !If [IsMultiAz, true, false]
      
     
      # Backup
#snapshot      DeleteAutomatedBackups: true
      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
      PreferredBackupWindow: !If [UsesBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
      CopyTagsToSnapshot: !If [UsesBackup, true, !Ref AWS::NoValue]


      # Log & Monitoring
      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
#snapshot      MonitoringInterval: !If [UsesMonitoring, !Ref MonitoringIntervalParam, !Ref AWS::NoValue]
#snapshot      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]
#snapshot      EnablePerformanceInsights: false
#snapshot      PerformanceInsightsKMSKeyId: String
#snapshot      PerformanceInsightsRetentionPeriod: Number


      # Option
      DeletionProtection: false 
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindowParam      

      #Timezone: String

      #AssociatedRoles: 
      #  - DBInstanceRole
 
      #CACertificateIdentifier: String
      #CharacterSetName: String

      #Domain: String
      #DomainIAMRoleName: String
   
      #UseDefaultProcessorFeatures: String   
      #ProcessorFeatures: 
      #  - ProcessorFeature

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBIdentifierNameParam



Outputs:
  InstanceId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...


