---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # RDS Template
  * For AWS CloudFormation - RDS Template

  ## Resources
  1. 
  2. 
  3. 
  4. 

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "RDS Configuration"
        Parameters:
          - DBEngineNameParam
          - DBEngineVersionParam
      - Label:
          default: "Subnet Group Configuration"
        Parameters:
          - SubnetGroupNameParam
          - SubnetGroupNameParam
      - Label:
          default: "Parameter Group Configuration"
        Parameters:
          - ParameterGroupFamilyParam
          - ParameterGroupNameParam

      - Label:
          default: "Option Group Configuration"
        Parameters:
          - OptionGroupNameParam
          - 


#Mappings:


Parameters:
  DBEngineNameParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - mariadb
      - mysql
      - oracle-ee
      - oracle-ee-cdb  
      - oracle-se2
      - oracle-cdb
      - postgres
      - sqlserver-ee
      - sqlserver-se
      - sqlserver-ex
      - sqlserver-web
  DBEngineVersionParam:
    Description: 'DB Engine Version'
    Type: String
    AllowedValues:


  SubnetGroupNameParam:
    Description: "Subnet Group Name"
    Type: String
    Default: "null"
  SubnetGroupSubnetIdsParam:
    Description: "Subnet ID"
    Type: List<AWS::EC2::Subnet::Id>

  ParameterGroupFamilyParam:
    Description: 'Parameter Group Family'
    Type: String
    AllowedValues:
      - aurora-mysql5.7
      - aurora-mysql8.0
      - aurora-postgresql11
      - aurora-postgresql12
      - aurora-postgresql13
      - mysql5.7
      - mysql8.0
      - oracle-ee-19
      - oracle-ee-cdb-19
      - oracle-se2-19
      - oracle-se2-cdb-19
      - postgres11
      - postgres12
      - postgres13
      - postgres14
      - sqlserver-ee-13.0
      - sqlserver-se-13.0
      - sqlserver-ex-13.0
      - sqlserver-web-13.0
  ParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: "null"

  OptionGroupNameParam:
    Description: 'Option Group Name'
    Type: String
    Default: "null"



#Rules:


Conditions:
  IsPubSub1: !Not [!Equals [!Select [0, !Ref PubSubAZList], ""]]

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: String
      EngineVersion: String 
      
      
      
      #AllocatedStorage: String
      #AllowMajorVersionUpgrade: Boolean
      AssociatedRoles: 
        - DBInstanceRole
      #AutoMinorVersionUpgrade: Boolean
      AvailabilityZone: String
      

      BackupRetentionPeriod: Integer
      CACertificateIdentifier: String
      CharacterSetName: String
      CopyTagsToSnapshot: Boolean
      DBClusterIdentifier: String
      DBInstanceClass: String
      DBInstanceIdentifier: String
      DBName: String
      DBParameterGroupName: String
      DBSecurityGroups: 
        - String
      DBSnapshotIdentifier: String
      DBSubnetGroupName: String
      DeleteAutomatedBackups: Boolean
      DeletionProtection: Boolean
      Domain: String
      DomainIAMRoleName: String
      EnableCloudwatchLogsExports: 
        - String
      EnableIAMDatabaseAuthentication: Boolean
      EnablePerformanceInsights: Boolean

      Iops: Integer
      KmsKeyId: String
      LicenseModel: String
      MasterUsername: String
      MasterUserPassword: String
      MaxAllocatedStorage: Integer
      MonitoringInterval: Integer
      MonitoringRoleArn: String
      MultiAZ: Boolean
      OptionGroupName: String
      PerformanceInsightsKMSKeyId: String
      PerformanceInsightsRetentionPeriod: Integer
      Port: String
      PreferredBackupWindow: String
      PreferredMaintenanceWindow: String
      ProcessorFeatures: 
        - ProcessorFeature
      PromotionTier: Integer
      PubliclyAccessible: Boolean
      SourceDBInstanceIdentifier: String
      SourceRegion: String
      StorageEncrypted: Boolean
      StorageType: String

      Timezone: String
      UseDefaultProcessorFeatures: Boolean
      VPCSecurityGroups: 
        - String
      Tags: 
        - Tag        

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: !Sub 'Subnet Group for ${SubnetGroupNameParam}'
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      SubnetIds: !Ref SubnetGroupSubnetIdsParam
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref SubnetGroupSubnetIdsParam

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: !Sub 'Subnet Group for ${ParameterGroupNameParam}'
      Family: !Ref ParameterGroupFamilyParam
      #Parameters: 
      #  Key : Value
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref ParameterGroupNameParam

  DBOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties: 
      EngineName: String
      MajorEngineVersion: String
      #OptionConfigurations: 
      #  - OptionConfiguration
      OptionGroupDescription: !Sub 'Subnet Group for ${OptionGroupNameParam}'
      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref OptionGroupNameParam














  PubSub1: 
    Type: 'AWS::EC2::Subnet'
    Condition: IsPubSub1
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [0, !Ref PubSubAZList]
      CidrBlock: !Select [0, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [0, !Ref PubSubNameList]

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Condition: IsPubSub1
    Properties:
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join
            - ''
            - - 'igw-'
              - !Ref NameInfix
  AttachInternetGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Condition: IsPubSub1
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PubRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Condition: IsPubSub1
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: Fn::Join
            - ''
            - - 'rt-'
              - !Ref NameInfix
              - '-pub'
  PubSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPubSub1
    Properties:
      SubnetId: !Ref PubSub1
      RouteTableId: !Ref PubRouteTable
  PubRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway  
  
  TestSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '2073'
          ToPort: '2073'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '40022'
          ToPort: '40022'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: Fn::Join
            - ''
            - - 'sg-'
              - !Ref NameInfix
              - '-default'


Outputs:
  InstanceId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...


