---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Aurora Cluster Template
  * For AWS CloudFormation - Aurora Cluster Template


  ## DB Engine
  * MySQL
  * Postgres


  ## Resources
  1. 
  2. DB Storage Type
    * Only gp2
  3. 
  4. 


  ## Parameter


  ## Create Aurora
  * Basic => Aurora Cluster & Write/Read Instance
  * Snapshot => Restore
  * SourceDB & ResotreType => Clone
  * ReplicationSourceIdentifier => Cross-Region Read Replica

#SnapshotIdentifier: !Ref DBSnapshotIdentifierParam

#ReplicationSourceIdentifier: !Ref ReplicationSourceIdentifierParam
      
#SourceDBClusterInstanceIdentifier: !Ref SourceDBClusterIdentifierParam
#SourceRegion: !Ref SourceRegionParam
#RestoreType: !Ref RestoreTypeParam

#UseLatestRestorableTime: Boolean

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Aurora Cluster Configuration"
        Parameters:
          - DBClusterIdentifierParam
        #  - GlobalClusterIdentifierParam

      - 
        Label:
          default: "RDS Configuration"
        Parameters:
          - DBIdentifierNameParam
          - DBInstanceClassParam
          - PromotionTierParam

      #- 
      #  Label:
      #    default: "Snapshot & Replica & Restore Configuration"
      #  Parameters:          
      #    - DBSnapshotIdentifierParam
      #    - SourceDBClusterIdentifierParam
      #    - SourceRegionParam

      - 
        Label:
          default: "Storage Configuration"
        Parameters:
          - KmsKeyParam

      - 
        Label:
          default: "Database Configuration"
        Parameters:
          - EngineParam
          - EngineVersionParam
          - DatabaseNameParam
          - MasterUsernameParam
          - MasterUserPasswordParam
          - PortParam
          - ClusterParameterGroupNameParam
          - ParameterGroupNameParam
          - CACertificateIdentifierParam

      - 
        Label:
          default: "Network Configuration"
        Parameters:
          - PubliclyAccessibleParam
          - SubnetGroupNameParam
          - AzParam
          - SecurityGroupListParam

      - 
        Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriodParam
          - PreferredBackupWindowParam

      - 
        Label:
          default: "Log & Maintenance Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
          - PreferredMaintenanceWindowParam
          - MonitoringIntervalParam
          - MonitoringRoleArnParam


    #ParameterLabels:
    #  DBClusterIdentifierParam: 
    #    default: "Which VPC should this be deployed to?"


Mappings:
  DBEngineMap:
    aurora:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-postgresql:
      Log:
        - postgresql



Parameters:
  DBClusterIdentifierParam:
    Description: 'Aurora Cluster Name'
    Type: String
    Default: 'rds-y2-test-cluster'
#  GlobalClusterIdentifierParam:
#    Description: 'Aurora Global Cluster Name'
#    Type: String
#    Default: 'null'
  DBIdentifierNameParam:
    Description: 'RDS Identifier Name / If input abc, DB ID is <AuroraClusterName + - + abc>'
    Type: String
    Default: 'null'
  DBInstanceClassParam:
    Description: 'DB Instance Class'
    Type: String
    Default: db.r3.large
    AllowedValues:
      - db.r3.large
      - db.t3.medium
      - db.t3.large
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge   
  PromotionTierParam:
    Description: 'Promotion Tier : 0 ~ 15 (Default: 1)/ for failover'
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 15


#  DBSnapshotIdentifierParam:
#    Description: 'Snapshot ARN. Create db using Snapshot'
#    Type: String
#    Default: 'null'
#  SourceDBClusterIdentifierParam:
#    Description: 'Source DB Cluster ID, Create Replica'
#    Type: String
#    Default: 'null'
#  SourceRegionParam:
#    Description: 'Source DB Region, Create Replica'
#    Type: String
#    Default: 'null'
#    AllowedValues:
#      - 'null'
#      - 'us-west-1'
#      - 'us-east-1'
#      - 'ap-northeast-2'

  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - aurora
      - aurora-mysql
      - aurora-postgresql
  EngineVersionParam:
    Description: 'DB Engine Version'
    Type: String
    Default: '5.7.mysql_aurora.2.10.0'
    #AllowedValues:
    #  - 

  DatabaseNameParam:
    Description: 'Database Name'
    Type: String
    Default: 'database12'   
  MasterUsernameParam:
    Description: 'Master Username'
    Type: String
    Default: 'test12'
  MasterUserPasswordParam:
    Description: 'Master User Password'
    Type: String
    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '5432'
  ClusterParameterGroupNameParam:
    Description: 'Cluster Parameter Group Name'
    Type: String
    Default: 'null'
  ParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: 'null'
  CACertificateIdentifierParam:
    Description: 'CA Certification / null == rds-ca-2019'
    Type: String
    Default: 'null'



  # Network
  PubliclyAccessibleParam:
    Description: 'Can publicly access db? (ex> true,false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false  
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-cluster-y2-test'
  AzParam:
    Description: 'Availability Zone'
    Type: AWS::EC2::AvailabilityZone::Name
    Default: 'null'
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: CommaDelimitedList
    #Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  KmsKeyParam:
    Description: "KMS Key ID  / null == No encryption"
    Type: String
    Default: "null"

            
  # Backup
  BackupRetentionPeriodParam:
    Description: 'Backup Retention Period: 1 ~ 35 (Day)'
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 35
  PreferredBackupWindowParam:
    Description: 'Backup Window(UTC): hh24:mi-hh24:mi (ex> 00:30-01:30)'
    Type: String
    Default: '17:00-17:30'


  # Log & Maintenance Configuration
  EnableCloudwatchLogsExportParam:
    Description: 'Does db use CloudWatch Logs? (ex> true/false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  PreferredMaintenanceWindowParam:
    Description: 'Maintenance Setting(UTC): ddd:hh24:mi-ddd:hh24:mi (ex> wed:07:30-wed:08:00)'
    Type: String
    Default: 'sat:16:00-sat:16:30'
  MonitoringIntervalParam:
    Description: 'Monitoring Interval: 0, 1, 5, 10, 15, 30, 60 (Second) / 0 == Not use monitoring'
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
      - 5
      - 10
      - 15
      - 30
      - 60
  MonitoringRoleArnParam:
    Description: 'Monitoring Role ARN / Input value, when MonitoringIntervalParam is not 0'
    Type: String
    Default: 'null'

#Rules:


Conditions:
  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
  SupportsSSLTLS: !Not [!Equals [!Ref CACertificateIdentifierParam, 'null']]
  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogsExportParam, true]
  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]


Resources:
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      # DB Cluster
      DBClusterIdentifier: !Ref DBClusterIdentifierParam
      #GlobalClusterIdentifier: !Ref GlobalClusterIdentifierParam # Not use other region
      Engine: !Ref EngineParam
      EngineVersion: !Ref EngineVersionParam
      EngineMode: 'provisioned'

      DatabaseName: !Ref DatabaseNameParam
      MasterUsername: !Ref MasterUsernameParam
      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam
      DBClusterParameterGroupName: !Ref ClusterParameterGroupNameParam

      #EnableIAMDatabaseAuthentication: String
      #AssociatedRoles: 
      #  - DBInstanceRole
 

      # Snapshot & Replica & Restore
      #SnapshotIdentifier: !Ref DBSnapshotIdentifierParam
      #ReplicationSourceIdentifier: !Ref ReplicationSourceIdentifierParam
      
      #SourceDBClusterInstanceIdentifier: !Ref SourceDBClusterIdentifierParam
      #SourceRegion: !Ref SourceRegionParam

      #RestoreType: !Ref RestoreTypeParam
      

      #UseLatestRestorableTime: Boolean
      #ScalingConfiguration: #Serverless
      #  AutoPause: Boolean
      #  MaxCapacity: Integer
      #  MinCapacity: Integer
      #  SecondsUntilAutoPause: Integer



      # Storage
      StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      DBSubnetGroupName: !Ref SubnetGroupNameParam
#      AvailabilityZones: !Ref AzsParam
      VpcSecurityGroupIds: !Ref SecurityGroupListParam

  
      # Backup
      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
      PreferredBackupWindow: !Ref PreferredBackupWindowParam
      CopyTagsToSnapshot: true


      # Log & Maintenance
      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindowParam
      #BacktrackWindows


      # Option
      DeletionProtection: true
      #EnableHttpEndpoint: Boolean # Only Serverless


      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBClusterIdentifierParam



  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DB Instance
      #DBClusterIdentifier: !Ref DBClusterIdentifierParam
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: !Ref DBIdentifierNameParam
      DBInstanceClass: !Ref DBInstanceClassParam
      PromotionTier: !Ref PromotionTierParam

      # Database      
      #Engine: !Ref EngineParam
      Engine: !Ref EngineParam
#aurora      EngineVersion: !Ref EngineVersionParam
#aurora      DBName: !Ref DatabaseNameParam
#aurora      MasterUsername: !Ref MasterUsernameParam
#aurora      MasterUserPassword: !Ref MasterUserPasswordParam
#aurora      Port: !Ref PortParam
      DBParameterGroupName: !Ref ParameterGroupNameParam
      #Timezone: !Ref TimezoneParam
      #CharacterSetName: !Ref CharacterSetNameParam
      CACertificateIdentifier: !If [SupportsSSLTLS, !Ref CACertificateIdentifierParam, !Ref AWS::NoValue]

#aurora      #EnableIAMDatabaseAuthentication: String
      #AssociatedRoles: 
      #  - DBInstanceRole
 

      # Snapshot & Read Replica
      #DBSnapshotIdentifier: !Ref DBSnapshotIdentifierParam
      #SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifierParam
      #SourceRegion: !Ref SourceRegionParam


      # Storage
      #StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
      #KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PubliclyAccessibleParam
#aurora      DBSubnetGroupName: !Ref SubnetGroupNameParam
#aurora      AvailabilityZone: !If [IsMultiAz, !Ref AWS::NoValue, !Ref AzParam]
      AvailabilityZone: !Ref AzParam
#aurora      VPCSecurityGroups: !Ref SecurityGroupListParam


      # Availability
#aurora      MultiAZ: !If [IsMultiAz, true, false]
      
     
      # Backup
      DeleteAutomatedBackups: true
#aurora      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
#aurora      PreferredBackupWindow: !If [SupportsBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
#aurora      CopyTagsToSnapshot: !If [SupportsBackup, true, !Ref AWS::NoValue]


      # Log & Monitoring & Maintenance
#aurora      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
      MonitoringInterval: !If [UsesMonitoring, !Ref MonitoringIntervalParam, !Ref AWS::NoValue]
      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindowParam
      EnablePerformanceInsights: false
      #PerformanceInsightsKMSKeyId: String
      #PerformanceInsightsRetentionPeriod: Number


      # Option
#aurora      DeletionProtection: true
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false

      #Domain: String
      #DomainIAMRoleName: String
   
      #UseDefaultProcessorFeatures: String   
      #ProcessorFeatures: 
      #  - ProcessorFeature

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBIdentifierNameParam


Outputs:
  ClusterId:
    Description: Aurora Cluster ID
    Value: !Ref AuroraCluster
    Export:
      Name: !Sub "${AWS::StackName}-AuroraClusterId"

  ClusterEngine:
    Description: 'Aurora Cluster DB Engine'
    Value: !Ref EngineParam
    Export:
      Name: !Sub "${AWS::StackName}-AuroraDBEngine"

  RDSId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...