---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Aurora Cluster Template
  * For AWS CloudFormation - Aurora Cluster Template

  ## DB Information
  * Master User : <id>
  * Default Password : <pw>
  * Default DatabaseName : <db_name> 


  ## DB Engine
  * MySQL
  * Postgres


  ## Resources
  1. 
  2. DB Storage Type
    * Only gp2
  3. 
  4. 


  ## Not Use Parameter for using snapshot
  * GlobalClusterIdentifier
  * MasterUsername
  * ReplicationSourceIdentifier
  * RestoreType
  * SourceDBClusterIdentifier
  * SourceRegion
  * StorageEncrypted
  * UseLatestRestorableTime


  ## Create Aurora
  * Basic => Aurora Cluster & Write/Read Instance
  * Snapshot => Restore
  * SourceDB & ResotreType => Clone
  * ReplicationSourceIdentifier => Cross-Region Read Replica


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Aurora Cluster Configuration"
        Parameters:
          - DBClusterIdentifierParam
        #  - GlobalClusterIdentifierParam

      - 
        Label:
          default: "Snapshot & Replica & Restore Configuration"
        Parameters:          
          - DBSnapshotIdentifierParam
        #  - SourceDBClusterIdentifierParam
        #  - SourceRegionParam
        #  - RestoreType

      - 
        Label:
          default: "Storage Configuration"
        Parameters:
          - KmsKeyParam

      - 
        Label:
          default: "Database Configuration"
        Parameters:
          - EngineParam
          - EngineVersionParam
#snapshot          - DatabaseNameParam
#snapshot          - MasterUsernameParam
#snapshot          - MasterUserPasswordParam
          - PortParam
          - ClusterParameterGroupNameParam

      - 
        Label:
          default: "Network Configuration"
        Parameters:
          - SubnetGroupNameParam
#          - AzsParam
          - SecurityGroupListParam

      - 
        Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriodParam
          - PreferredBackupWindowParam

      - 
        Label:
          default: "Log & Maintenance Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
          - PreferredMaintenanceWindowParam

    #ParameterLabels:
    #  DBClusterIdentifierParam: 
    #    default: "Which VPC should this be deployed to?"


Mappings:
  DBEngineMap:
    aurora:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-postgresql:
      Log:
        - postgresql



Parameters:
  DBClusterIdentifierParam:
    Description: 'Aurora Cluster Name'
    Type: String
    AllowedPattern: "^(\\w|-)+$"
    Default: 'rds-y2-test-cluster'
#  GlobalClusterIdentifierParam:
#    Description: 'Aurora Global Cluster Name'
#    Type: String
#    Default: 'null'   
  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - aurora
      - aurora-mysql
      - aurora-postgresql
  EngineVersionParam:
    Description: 'DB Engine Version'
    Type: String
    Default: '5.7.mysql_aurora.2.10.0'
    #AllowedValues:
    #  - 


  DBSnapshotIdentifierParam:
    Description: 'Snapshot ARN. Create db using Snapshot'
    Type: String
    AllowedPattern: "^(arn:aws:rds:)(\\w|-|:)+$"
#  SourceDBClusterIdentifierParam:
#    Description: 'Source DB Cluster ID, Create Replica'
#    Type: String
#    Default: 'null'
#  SourceRegionParam:
#    Description: 'Source DB Region, Create Replica'
#    Type: String
#    Default: 'null'
#    AllowedValues:
#      - 'null'
#      - 'us-west-1'
#      - 'us-east-1'
#      - 'ap-northeast-2'

#snapshot  DatabaseNameParam:
#    Description: 'Database Name'
#    Type: String
#    Default: 'database12'   
#snapshot  MasterUsernameParam:
#    Description: 'Master Username'
#    Type: String
#    Default: 'test12'
#snapshot  MasterUserPasswordParam:
#    Description: 'Master User Password'
#    Type: String
#    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '15432'
    AllowedPattern: "^(\\d)+$"
  ClusterParameterGroupNameParam:
    Description: 'Cluster Parameter Group Name'
    Type: String
    Default: 'null'
    AllowedPattern: "^(\\w|-)+$"



  # Network
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-cluster-y2-test'
    AllowedPattern: "^(\\w|-)+$"
#  AzsParam:
#    Description: 'Availability Zones'
#    Type: List<AWS::EC2::AvailabilityZone::Name>
#    Default: 'null'
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  KmsKeyParam:
    Description: "KMS Key ID  / null == No encryption"
    Type: String

            
  # Backup
  BackupRetentionPeriodParam:
    Description: 'Backup Retention Period: 1 ~ 35 (Day)'
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 35
  PreferredBackupWindowParam:
    Description: 'Backup Window(UTC): hh24:mi-hh24:mi (ex> 00:30-01:30)'
    Type: String
    Default: '17:00-17:30'


  # Log & Maintenance Configuration
  EnableCloudwatchLogsExportParam:
    Description: 'Does db use CloudWatch Logs? (ex> true/false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  PreferredMaintenanceWindowParam:
    Description: 'Maintenance Setting(UTC): ddd:hh24:mi-ddd:hh24:mi (ex> wed:07:30-wed:08:00)'
    Type: String
    Default: 'sat:16:00-sat:16:30'


#Rules:


Conditions:
  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, '']]
  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogsExportParam, true]


Resources:
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      # DB Cluster
      DBClusterIdentifier: !Ref DBClusterIdentifierParam
      #GlobalClusterIdentifier: !Ref GlobalClusterIdentifierParam # Not use other region
      Engine: !Ref EngineParam
      EngineVersion: !Ref EngineVersionParam
      EngineMode: 'provisioned'

#snapshot      DatabaseName: !Ref DatabaseNameParam
#snapshot      MasterUsername: !Ref MasterUsernameParam
#snapshot      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam
      DBClusterParameterGroupName: !Ref ClusterParameterGroupNameParam

      #EnableIAMDatabaseAuthentication: String
      #AssociatedRoles: 
      #  - DBInstanceRole
 

      # Snapshot & Replica & Restore
      SnapshotIdentifier: !Ref DBSnapshotIdentifierParam
 
      #ReplicationSourceIdentifier: !Ref ReplicationSourceIdentifierParam
      
      #SourceDBClusterInstanceIdentifier: !Ref SourceDBClusterIdentifierParam
      #SourceRegion: !Ref SourceRegionParam
      #RestoreType: !Ref RestoreTypeParam
      

      #UseLatestRestorableTime: Boolean
      #ScalingConfiguration: #Serverless
      #  AutoPause: Boolean
      #  MaxCapacity: Integer
      #  MinCapacity: Integer
      #  SecondsUntilAutoPause: Integer



      # Storage
      StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      DBSubnetGroupName: !Ref SubnetGroupNameParam
#      AvailabilityZones: !Ref AzsParam
      VpcSecurityGroupIds: !Ref SecurityGroupListParam

  
      # Backup
      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
      PreferredBackupWindow: !Ref PreferredBackupWindowParam
      CopyTagsToSnapshot: true


      # Log & Maintenance
      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindowParam
      #BacktrackWindows


      # Option
      DeletionProtection: true
      #EnableHttpEndpoint: Boolean # Only Serverless


      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBClusterIdentifierParam



Outputs:
  ClusterId:
    Description: Aurora Cluster ID
    Value: !Ref AuroraCluster
    Export:
      Name: !Sub "${AWS::StackName}-AuroraClusterId"

  ClusterEngine:
    Description: 'Aurora Cluster DB Engine'
    Value: !Ref EngineParam
    Export:
      Name: !Sub "${AWS::StackName}-AuroraDBEngine"
...