---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Aurora Instance Template
  * For AWS CloudFormation - Auroara Instance Template

  ## DB Engine
  * MySQL
  * Postgres


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Aurora Cluster Configuration"
        Parameters:
          - AuroraStackNameParam
          - DBClusterIdentifierParam

      - 
        Label:
          default: "RDS Configuration"
        Parameters:
          - DBIdentifierNameParam
          - DBInstanceClassParam
          - PromotionTierParam

      #- 
      #  Label:
      #    default: "Snapshot & Read Replica Configuration"
      #  Parameters:          
      #    - DBSnapshotIdentifierParam
      #    - SourceDBInstanceIdentifierParam
      #    - SourceRegionParam

#aurora      - 
#aurora       Label:
#aurora         default: "Storage Configuration"
#aurora        Parameters:
#aurora          - StorageTypeParam
#aurora          - StorageSizeParam
          #- IopsParam
#aurora          - MaxAllocatedStorageParam
#aurora          - KmsKeyParam

      - 
        Label:
          default: "Database Configuration"
        Parameters:
          - EngineParam
#aurora          - EngineVersionParam
          #- LicenseModelParam        
#aurora          - DatabaseNameParam
#aurora          - MasterUsernameParam
#aurora          - MasterUserPasswordParam
#aurora          - PortParam
          - ParameterGroupNameParam
          - CACertificateIdentifierParam

#aurora      - 
#        Label:
#          default: "Network Configuration"
#        Parameters:
          - PubliclyAccessibleParam
#aurora          - SubnetGroupNameParam
          - AzParam
#aurora          - SecurityGroupListParam


      #-
      #  Label:
      #    default: "Availability Configuration"
      #  Parameters:
      #    - MultiAzParam


#aurora      - 
#        Label:
#          default: "Backup Configuration"
#        Parameters:
#aurora          - BackupRetentionPeriodParam
#aurora          - PreferredBackupWindowParam

      - 
        Label:
          default: "Log & Monitoring & Maintenance Configuration"
        Parameters:
#aurora          - EnableCloudwatchLogsExportParam
          - MonitoringIntervalParam
          - MonitoringRoleArnParam
          - PreferredMaintenanceWindowParam

    #ParameterLabels:
    #  DBIdentifierNameParam: 
    #    default: "Which VPC should this be deployed to?"


Mappings:
  DBEngineMap:
    aurora:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    aurora-postgresql:
      Log:
        - postgresql




Parameters:
  AuroraStackNameParam:
    Description: 'Aurora Cluster Stack'
    Type: String
    Default: 'null'
  DBClusterIdentifierParam:
    Description: 'Aurora Cluster Name'
    Type: String
    Default: 'null'
  DBIdentifierNameParam:
    Description: 'RDS Identifier Name / If input abc, DB ID is <AuroraClusterName + - + abc>'
    Type: String
    Default: 'null'
  DBInstanceClassParam:
    Description: 'DB Instance Class'
    Type: String
    Default: db.r3.large
    AllowedValues:
      - db.r3.large
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.8xlarge
      - db.m5.12xlarge
      - db.m5.16xlarge
      - db.t3.small
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
  PromotionTierParam:
    Description: 'Promotion Tier : 0 ~ 15 (Default: 1)/ for failover'
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 15


#  DBSnapshotIdentifierParam:
#    Description: 'Snapshot ARN. Create db using Snapshot'
#    Type: String
#    Default: 'null'
#  SourceDBInstanceIdentifierParam:
#    Description: 'Source DB ID, Create Read Replica'
#    Type: String
#    Default: 'null'
#  SourceRegionParam:
#    Description: 'Source DB Region, Create Read Replica'
#    Type: String
#    Default: 'null'
#    AllowedValues:
#      - 'null'
#      - 'us-west-1'
#      - 'us-east-1'
#      - 'ap-northeast-2'


  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - aurora
      - aurora-mysql
      - aurora-postgresql
#aurora  EngineVersionParam:
#    Description: 'DB Engine Version'
#    Type: String
#aurora  DatabaseNameParam:
#    Description: 'Database Name'
#    Type: String
#    Default: 'database12'
#aurora  MasterUsernameParam:
#    Description: 'Master Username'
#    Type: String
#    Default: 'test12'
#aurora  MasterUserPasswordParam:
#    Description: 'Master User Password'
#    Type: String
#    Default: 'testtest12!'
#aurora  PortParam:
#    Description: 'Database Port Number'
#    Type: String
#    Default: '5432'
  ParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: 'null'
  CACertificateIdentifierParam:
    Description: 'CA Certification / null == rds-ca-2019'
    Type: String
    Default: 'null'
    #AllowedValues: 


  # Network
  PubliclyAccessibleParam:
    Description: 'Can publicly access db? (ex> true,false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
#aurora  SubnetGroupNameParam:
#    Description: 'Subnet Group Name'
#    Type: String
#    Default: 'sg-y2-test'
  AzParam:
    Description: 'Availability Zone / If you check Multi AZ true, this changes to AWS::NoValue'
    Type: AWS::EC2::AvailabilityZone::Name
    Default: 'null'
#aurora  SecurityGroupListParam:
#    Description: 'Security Group List'
#    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
#aurora  KmsKeyParam:
#  Description: "KMS Key ID  / null == No encryption"
#    Type: String
#    Default: "null"


  # Availability
#aurora  MultiAzParam:
#    Description: 'Does RDS create multi az? (ex> true,false)'
#    Type: String
#    Default: false
#    AllowedValues:
#      - true
#      - false

            
  # Backup
#aurora  BackupRetentionPeriodParam:
#    Description: 'Backup Retention Period: 0 ~ 35 (Day) / 0 == Not use backup'
#    Type: Number
#    Default: 0
#    MinValue: 0
#    MaxValue: 35
#aurora  PreferredBackupWindowParam:
#    Description: 'Backup Window(UTC): hh24:mi-hh24:mi (ex> 00:30-01:30) / Input value, when BackupRetentionPeriodParam is not 0'
#    Type: String
#    Default: 'null'


  # Log & Monitoring & Maintenance Configuration
#aurora  EnableCloudwatchLogsExportParam:
#    Description: 'Does db use CloudWatch Logs? (ex> true/false)'
#    Type: String
#    Default: false
#    AllowedValues:
#      - true
#      - false
  MonitoringIntervalParam:
    Description: 'Monitoring Interval: 0, 1, 5, 10, 15, 30, 60 (Second) / 0 == Not use monitoring'
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
      - 5
      - 10
      - 15
      - 30
      - 60
  MonitoringRoleArnParam:
    Description: 'Monitoring Role ARN / Input value, when MonitoringIntervalParam is not 0'
    Type: String
    Default: 'null'
  PreferredMaintenanceWindowParam:
    Description: 'Maintenance Setting(UTC): ddd:hh24:mi-ddd:hh24:mi (ex> wed:07:30-wed:08:00)'
    Type: String
    Default: 'sat:16:00-sat:16:30'


#Rules:


Conditions:
#aurora  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
#aurora  IsMultiAz: !Equals [!Ref MultiAzParam, true]
  SupportsSSLTLS: !Not [!Equals [!Ref CACertificateIdentifierParam, 'null']]
#aurora  SupportsBackup: !Not [!Equals [!Ref BackupRetentionPeriodParam, 0]]
  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]
#aurora  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogsExportParam, true]
#aurora  IsPostgres: !Equals [!Ref EngineParam, 'postgres']


Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DB Instance
      #DBClusterIdentifier: !Ref DBClusterIdentifierParam
      DBClusterIdentifier: !ImportValue
        Fn::Sub: "${AuroraStackNameParam}-AuroraClusterId"
      DBInstanceIdentifier: !Join
        - '-'
        - - !ImportValue
              Fn::Sub: "${AuroraStackNameParam}-AuroraClusterId"
          -  !Ref DBIdentifierNameParam
      DBInstanceClass: !Ref DBInstanceClassParam
      PromotionTier: !Ref PromotionTierParam

      # Database      
      #Engine: !Ref EngineParam
      Engine: !ImportValue
        Fn::Sub: "${AuroraStackNameParam}-AuroraDBEngine"
#aurora      EngineVersion: !Ref EngineVersionParam
#aurora      DBName: !Ref DatabaseNameParam
#aurora      MasterUsername: !Ref MasterUsernameParam
#aurora      MasterUserPassword: !Ref MasterUserPasswordParam
#aurora      Port: !Ref PortParam
      DBParameterGroupName: !Ref ParameterGroupNameParam
      #Timezone: !Ref TimezoneParam
      #CharacterSetName: !Ref CharacterSetNameParam
      CACertificateIdentifier: !If [SupportsSSLTLS, !Ref CACertificateIdentifierParam, !Ref AWS::NoValue]

#aurora      #EnableIAMDatabaseAuthentication: String
      #AssociatedRoles: 
      #  - DBInstanceRole
 

      # Snapshot & Read Replica
      #DBSnapshotIdentifier: !Ref DBSnapshotIdentifierParam
      #SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifierParam
      #SourceRegion: !Ref SourceRegionParam


      # Storage
      #StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
      #KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PubliclyAccessibleParam
#aurora      DBSubnetGroupName: !Ref SubnetGroupNameParam
#aurora      AvailabilityZone: !If [IsMultiAz, !Ref AWS::NoValue, !Ref AzParam]
      AvailabilityZone: !Ref AzParam
#aurora      VPCSecurityGroups: !Ref SecurityGroupListParam


      # Availability
#aurora      MultiAZ: !If [IsMultiAz, true, false]
      
     
      # Backup
      DeleteAutomatedBackups: true
#aurora      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
#aurora      PreferredBackupWindow: !If [SupportsBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
#aurora      CopyTagsToSnapshot: !If [SupportsBackup, true, !Ref AWS::NoValue]


      # Log & Monitoring & Maintenance
#aurora      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
      MonitoringInterval: !If [UsesMonitoring, !Ref MonitoringIntervalParam, !Ref AWS::NoValue]
      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindowParam
      EnablePerformanceInsights: false
      #PerformanceInsightsKMSKeyId: String
      #PerformanceInsightsRetentionPeriod: Number


      # Option
#aurora      DeletionProtection: true
#aurora      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false

      #Domain: String
      #DomainIAMRoleName: String
   
      #UseDefaultProcessorFeatures: String   
      #ProcessorFeatures: 
      #  - ProcessorFeature

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBIdentifierNameParam


Outputs:
  RDSId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...


