---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Aurora Cluster Template
  * For AWS CloudFormation - Aurora Cluster Template


  ## DB Engine
  * MySQL
  * Postgres


  ## Resources
  1. 
  2. DB Storage Type
    * Only gp2
  3. 
  4. 


  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Aurora Cluster Configuration"
        Parameters:
          - DBClusterIdentifierParam
        #  - GlobalClusterIdentifierParam
          - EngineParam
          - EngineVersionParam

      #- 
      #  Label:
      #    default: "Snapshot & Replica & Restore Configuration"
      #  Parameters:          
      #    - DBSnapshotIdentifierParam
      #    - SourceDBClusterIdentifierParam
      #    - SourceRegionParam

      - 
        Label:
          default: "Storage Configuration"
        Parameters:
          - KmsKeyParam

      - 
        Label:
          default: "Database Configuration"
        Parameters:
          - DatabaseNameParam
          - MasterUsernameParam
          - MasterUserPasswordParam
          - PortParam
          - ClusterParameterGroupNameParam

      - 
        Label:
          default: "Network Configuration"
        Parameters:
          - SubnetGroupNameParam
          - AzsParam
          - SecurityGroupListParam

      - 
        Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriodParam
          - PreferredBackupWindowParam

      - 
        Label:
          default: "Log & Maintenance Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
          - PreferredMaintenanceWindowParam

    #ParameterLabels:
    #  DBClusterIdentifierParam: 
    #    default: "Which VPC should this be deployed to?"


Mappings:
  DBEngineMap:
    mariadb:
      Log:
        - audit
        - error
        - general
        - slowquery
    mysql:
      Log:
        - audit
        - error
        - general
        - slowquery
    oracle-ee:
      Log:
        - alert
        - audit
        - listener
        - trace
    oracle-ee-cdb:
      Log: 
        - alert
        - audit
        - listener
        - trace
    oracle-se2:
      Log:
        - alert
        - audit
        - listener
        - trace
    oracle-cdb:
      Log:
        - alert
        - audit
        - listener
        - trace
    postgres:
      Log:
        - postgresql
        - upgrade
    sqlserver-ee:
      Log:
        - agent
        - error
    sqlserver-se:
      Log:
        - agent
        - error
    sqlserver-ex:
      Log:
        - agent
        - error
    sqlserver-web:
      Log:
        - agent
        - error


Parameters:
  DBClusterIdentifierParam:
    Description: 'Aurora Cluster Name'
    Type: String
    Default: 'rds-y2-test'
#  GlobalClusterIdentifierParam:
#    Description: 'Aurora Global Cluster Name'
#    Type: String
#    Default: 'null'   
  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - aurora
      - aurora-mysql
      - aurora-postgresql
  EngineVersionParam:
    Description: 'DB Engine Version'
    Type: String



#  DBSnapshotIdentifierParam:
#    Description: 'Snapshot ARN. Create db using Snapshot'
#    Type: String
#    Default: 'null'
#  SourceDBClusterIdentifierParam:
#    Description: 'Source DB Cluster ID, Create Replica'
#    Type: String
#    Default: 'null'
#  SourceRegionParam:
#    Description: 'Source DB Region, Create Replica'
#    Type: String
#    Default: 'null'
#    AllowedValues:
#      - 'null'
#      - 'us-west-1'
#      - 'us-east-1'
#      - 'ap-northeast-2'

  DatabaseNameParam:
    Description: 'Database Name'
    Type: String
    Default: 'database12'   
  MasterUsernameParam:
    Description: 'Master Username'
    Type: String
    Default: 'test12'
  MasterUserPasswordParam:
    Description: 'Master User Password'
    Type: String
    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '5432'
  ClusterParameterGroupNameParam:
    Description: 'Cluster Parameter Group Name'
    Type: String
    Default: 'null'



  # Network
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-y2-test'
  AzsParam:
    Description: 'Availability Zones'
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Default: 'null'
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  KmsKeyParam:
    Description: "KMS Key ID  / null == No encryption"
    Type: String
    Default: "null"

            
  # Backup
  BackupRetentionPeriodParam:
    Description: 'Backup Retention Period: 0 ~ 35 (Day) / 0 == Not use backup'
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 35
  PreferredBackupWindowParam:
    Description: 'Backup Window(UTC): hh24:mi-hh24:mi (ex> 00:30-01:30) / Input value, when BackupRetentionPeriodParam is not 0'
    Type: String
    Default: 'null'


  # Log & Maintenance Configuration
  EnableCloudwatchLogsExportParam:
    Description: 'Does db use CloudWatch Logs? (ex> true/false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  PreferredMaintenanceWindowParam:
    Description: 'Maintenance Setting(UTC): ddd:hh24:mi-ddd:hh24:mi (ex> wed:07:30-wed:08:00)'
    Type: String
    Default: 'sun:01:00-sun:01:30'


#Rules:


Conditions:
  IncreasesStroage: !Not [!Equals [!Ref MaxAllocatedStorageParam, 0]]
  IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
  SupportsBackup: !Not [!Equals [!Ref BackupRetentionPeriodParam, 0]]
  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogsExportParam, true]
  IsPostgres: !Equals [!Ref EngineParam, 'postgres']


Resources:
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      # DB Cluster
      DBClusterIdentifier: !Ref DBClusterIdentifierParam
      #GlobalClusterIdentifier: !Ref GlobalClusterIdentifierParam # Not use other region
      DBInstanceClass: !Ref DBInstanceClassParam      
      Engine: !Ref EngineParam
      EngineVersion: !Ref EngineVersionParam
      EngineMode: 'provisioned'

      DatabaseName: !Ref DatabaseNameParam
      MasterUsername: !Ref MasterUsernameParam
      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam
      DBClusterParameterGroupName: !Ref ClusterParameterGroupNameParam

      #EnableIAMDatabaseAuthentication: String
      #AssociatedRoles: 
      #  - DBInstanceRole
 

      # Snapshot & Replica & Restore
      #SnapshotIdentifier: !Ref DBSnapshotIdentifierParam
      #ReplicationSourceIdentifier: !Ref ReplicationSourceIdentifierParam
            
      #SourceDBClusterInstanceIdentifier: !Ref SourceDBClusterIdentifierParam
      #SourceRegion: !Ref SourceRegionParam

      #RestoreType: !Ref RestoreTypeParam
      
      #UseLatestRestorableTime: Boolean
      #ScalingConfiguration: 
      # ScalingConfiguration


      # Storage
      StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
      KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      AvailabilityZones: !Ref AzsParam
      VpcSecurityGroupIds: !Ref SecurityGroupListParam

  
      # Backup
      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
      PreferredBackupWindow: !If [SupportsBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
      CopyTagsToSnapshot: !If [SupportsBackup, true, !Ref AWS::NoValue]


      # Log & Maintenance
      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindowParam
      #BacktrackWindows


      # Option
      DeletionProtection: true
      #EnableHttpEndpoint: Boolean # Only Serverless


      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBClusterIdentifier





Outputs:
  ClusterId:
    Description: Aurora Cluster ID
    Value: !Ref AuroraCluster
    Export:
      Name: !Sub "${AWS::StackName}-AuroraClusterId"

...