---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Aurora Instance Template
  * For AWS CloudFormation - Auroara Instance Template

  ## DB Engine
  * MySQL
  * Postgres


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Aurora Cluster Configuration"
        Parameters:
          - DBClusterIdentifierParam


      - 
        Label:
          default: "RDS Configuration"
        Parameters:
          - DBIdentifierNameParam
          - DBInstanceClassParam

      #- 
      #  Label:
      #    default: "Snapshot & Read Replica Configuration"
      #  Parameters:          
      #    - DBSnapshotIdentifierParam
      #    - SourceDBInstanceIdentifierParam
      #    - SourceRegionParam

      #- 
      #  Label:
      #    default: "Storage Configuration"
      #  Parameters:
      #    - KmsKeyParam

      - 
        Label:
          default: "Database Configuration"
        Parameters:
          #- DatabaseNameParam
          #- MasterUsernameParam
          - MasterUserPasswordParam
          - PortParam
          - ParameterGroupNameParam
          - CACertificateIdentifierParam

      - 
        Label:
          default: "Network Configuration"
        Parameters:
          - PubliclyAccessibleParam
          - SubnetGroupNameParam
          - AzParam
          - SecurityGroupListParam


      #-
      #  Label:
      #    default: "Availability Configuration"
      #  Parameters:
      #    - MultiAzParam


      - 
        Label:
          default: "Backup Configuration"
        Parameters:
          - BackupRetentionPeriodParam
          - PreferredBackupWindowParam

      - 
        Label:
          default: "Log & Monitoring & Maintenance Configuration"
        Parameters:
          - EnableCloudwatchLogsExportParam
          - MonitoringIntervalParam
          - MonitoringRoleArnParam
          - PreferredMaintenanceWindowParam

    #ParameterLabels:
    #  DBIdentifierNameParam: 
    #    default: "Which VPC should this be deployed to?"


Mappings:
  DBEngineMap:




Parameters:
  DBClusterIdentifierParam:
    Description: 'Aurora Cluster Name'
    Type: String
    Default: 'rds-y2-test-cluster'
  DBIdentifierNameParam:
    Description: 'RDS Identifier Name'
    Type: String
    Default: 'rds-y2-test'
  DBInstanceClassParam:
    Description: 'DB Instance Class'
    Type: String
    Default: db.m5.large
    AllowedValues: 
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.8xlarge
      - db.m5.12xlarge
      - db.m5.16xlarge
      - db.t3.small
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
  EngineParam:
    Description: 'DB Engine Name'
    Type: String
    AllowedValues:
      - mariadb
      - mysql
      - oracle-ee
      - oracle-ee-cdb  
      - oracle-se2
      - oracle-cdb
      - postgres
      - sqlserver-ee
      - sqlserver-se
      - sqlserver-ex
      - sqlserver-web
  EngineVersionParam:
    Description: 'DB Engine Version'
    Type: String



#  DBSnapshotIdentifierParam:
#    Description: 'Snapshot ARN. Create db using Snapshot'
#    Type: String
#    Default: 'null'
#  SourceDBInstanceIdentifierParam:
#    Description: 'Source DB ID, Create Read Replica'
#    Type: String
#    Default: 'null'
#  SourceRegionParam:
#    Description: 'Source DB Region, Create Read Replica'
#    Type: String
#    Default: 'null'
#    AllowedValues:
#      - 'null'
#      - 'us-west-1'
#      - 'us-east-1'
#      - 'ap-northeast-2'

#  DatabaseNameParam:
#    Description: 'Database Name'
#    Type: String
#    Default: 'database12'
  MasterUsernameParam:
    Description: 'Master Username'
    Type: String
    Default: 'test12'
  MasterUserPasswordParam:
    Description: 'Master User Password'
    Type: String
    Default: 'testtest12!'
  PortParam:
    Description: 'Database Port Number'
    Type: String
    Default: '5432'
  ParameterGroupNameParam:
    Description: 'Parameter Group Name'
    Type: String
    Default: 'null'
  CACertificateIdentifierParam:
    Description: 'CA Certification / null == rds-ca-2019'
    Type: String
    Default: 'null'
    #AllowedValues: 


  # Network
  PubliclyAccessibleParam:
    Description: 'Can publicly access db? (ex> true,false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  SubnetGroupNameParam:
    Description: 'Subnet Group Name'
    Type: String
    Default: 'sg-y2-test'
  AzParam:
    Description: 'Availability Zone / If you check Multi AZ true, this changes to AWS::NoValue'
    Type: AWS::EC2::AvailabilityZone::Name
    Default: 'null'
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: List<AWS::EC2::SecurityGroup::Id>


  # Storage
  #KmsKeyParam:
  #  Description: "KMS Key ID  / null == No encryption"
  #  Type: String
  #  Default: "null"


  # Availability
  MultiAzParam:
    Description: 'Does RDS create multi az? (ex> true,false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

            
  # Backup
  BackupRetentionPeriodParam:
    Description: 'Backup Retention Period: 0 ~ 35 (Day) / 0 == Not use backup'
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 35
  PreferredBackupWindowParam:
    Description: 'Backup Window(UTC): hh24:mi-hh24:mi (ex> 00:30-01:30) / Input value, when BackupRetentionPeriodParam is not 0'
    Type: String
    Default: 'null'


  # Log & Monitoring & Maintenance Configuration
  EnableCloudwatchLogsExportParam:
    Description: 'Does db use CloudWatch Logs? (ex> true/false)'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  MonitoringIntervalParam:
    Description: 'Monitoring Interval: 0, 1, 5, 10, 15, 30, 60 (Second) / 0 == Not use monitoring'
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
      - 5
      - 10
      - 15
      - 30
      - 60
  MonitoringRoleArnParam:
    Description: 'Monitoring Role ARN / Input value, when MonitoringIntervalParam is not 0'
    Type: String
    Default: 'null'
  PreferredMaintenanceWindowParam:
    Description: 'Maintenance Setting(UTC): ddd:hh24:mi-ddd:hh24:mi (ex> wed:07:30-wed:08:00)'
    Type: String
    Default: 'sun:01:00-sun:01:30'


#Rules:


Conditions:
  #IsEncrypted: !Not [!Equals [!Ref KmsKeyParam, 'null']]
  IsMultiAz: !Equals [!Ref MultiAzParam, true]
  SupportsSSLTLS: !Not [!Equals [!Ref CACertificateIdentifierParam, 'null']]
  SupportsBackup: !Not [!Equals [!Ref BackupRetentionPeriodParam, 0]]
  UsesMonitoring: !Not [!Equals [!Ref MonitoringIntervalParam, 0]]
  UsesCloudwatchLogsExport: !Equals [!Ref EnableCloudwatchLogsExportParam, true]
  IsPostgres: !Equals [!Ref EngineParam, 'postgres']


Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DB Instance
      DBClusterIdentifier: !Ref DBClusterIdentifierParam
      #DBInstanceIdentifier: !Ref DBIdentifierNameParam
      DBInstanceClass: !Ref DBInstanceClassParam      
      Engine: !Ref EngineParam
      EngineVersion: !Ref EngineVersionParam


      DBName: !Ref DatabaseNameParam
      MasterUsername: !Ref MasterUsernameParam
      MasterUserPassword: !Ref MasterUserPasswordParam
      Port: !Ref PortParam
      DBParameterGroupName: !Ref ParameterGroupNameParam
      #Timezone: !Ref TimezoneParam
      #CharacterSetName: !Ref CharacterSetNameParam
      CACertificateIdentifier: !If [SupportsSSLTLS, !Ref CACertificateIdentifierParam, !Ref AWS::NoValue]

      #EnableIAMDatabaseAuthentication: String
      #AssociatedRoles: 
      #  - DBInstanceRole
 

      # Snapshot & Read Replica
      #DBSnapshotIdentifier: !Ref DBSnapshotIdentifierParam
      #SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifierParam
      #SourceRegion: !Ref SourceRegionParam


      # Storage
      #StorageEncrypted: !If [IsEncrypted, true, !Ref AWS::NoValue]
      #KmsKeyId: !If [IsEncrypted, !Ref KmsKeyParam, !Ref AWS::NoValue]


      # Network
      PubliclyAccessible: !Ref PubliclyAccessibleParam
      DBSubnetGroupName: !Ref SubnetGroupNameParam
      AvailabilityZone: !If [IsMultiAz, !Ref AWS::NoValue, !Ref AzParam]
      VPCSecurityGroups: !Ref SecurityGroupListParam


      # Availability
      MultiAZ: !If [IsMultiAz, true, false]
      
     
      # Backup
      DeleteAutomatedBackups: true
      BackupRetentionPeriod: !Ref BackupRetentionPeriodParam
      PreferredBackupWindow: !If [SupportsBackup, !Ref PreferredBackupWindowParam, !Ref AWS::NoValue]
      CopyTagsToSnapshot: !If [SupportsBackup, true, !Ref AWS::NoValue]


      # Log & Monitoring & Maintenance
      EnableCloudwatchLogsExports: !If [UsesCloudwatchLogsExport, !FindInMap [DBEngineMap, !Ref EngineParam, Log], !Ref AWS::NoValue]
      MonitoringInterval: !If [UsesMonitoring, !Ref MonitoringIntervalParam, !Ref AWS::NoValue]
      MonitoringRoleArn: !If [UsesMonitoring, !Ref MonitoringRoleArnParam, !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindowParam
      EnablePerformanceInsights: false
      #PerformanceInsightsKMSKeyId: String
      #PerformanceInsightsRetentionPeriod: Number


      # Option
      DeletionProtection: true
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: false

      #Domain: String
      #DomainIAMRoleName: String
   
      #UseDefaultProcessorFeatures: String   
      #ProcessorFeatures: 
      #  - ProcessorFeature

      Tags: 
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref DBIdentifierNameParam


Outputs:
  RDSId:
    Description: RDS ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${AWS::StackName}-RdsId"
...


