---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # VPC Template
  * For AWS CloudFormation - VPC Template

  ## Resources
  1. VPC
  2. Public/Private Subnet
  3. Public/Private Route & Routing Table
  4. Internet Gateway

  ## 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "VPC Configuration"
        Parameters:
          - VpcName
          - VpcCidr
      - 
        Label:
          default: "Subnet Configuration"
        Parameters:
          - PubSubNum
          - PubSubNameList
          - PubSubCidrList
          - PubSubAZList
          - PriSubNum
          - PriSubNameList
          - PriSubCidrList
          - PriSubAZList

Parameters:
  VpcName:
    Description: Name of VPC
    Type: String
    Default: "vpc-y2-test"
  VpcCidr:
    Description: CIDR of VPC
    Type: String
    Default: "10.0.0.0/16"
    ConstraintDescription: "Parameter must only contain "
  PubSubNum:
    Description: Number of Public Subnet
    Type: Number
    ConstraintDescription: "Parameter must only contain "
  PubSubNameList:
    Description: "Name List of Public Subnet"
    Type: String 
  PubSubCidrList:
    Description: "CIDR List of Public Subnet"
    Type: CommaDelimitedList
  PubSubAZList:
    Description: "AZ List of Public Subnet"
    Type: CommaDelimitedList
  PriSubNum:
    Description: Number of Private Subnet
    Type: Number
    ConstraintDescription: "Parameter must only contain "
  PriSubNameList:
    Description: "Name List of Private Subnet"
    Type: CommaDelimitedList                                         
  PriSubCidrList:
    Description: "CIDR List of Private Subnet"
    Type: CommaDelimitedList
  PriSubAZList:
    Description: "AZ List of Private Subnet"
    Type: CommaDelimitedList

Conditions:
  IsPubSub1: !Not
    - !Equals
      - !Select
        - 0
        - !Ref PubSubAZList
      - ""

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: CloudFormationStack
          Value: !Ref AWS::StackId
        - Key: Name
          Value: !Ref VpcName
  PubSub1: 
    Type: 'AWS::EC2::Subnet'
    Condition: IsPubSub1
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select
            - 0
            - !Ref PubSubAZList
      CidrBlock: !Select 
        - 0
        - !Ref PubSubCidrList
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select
            - 0
            - !Ref PubSubNameList
Outputs:
  Test:
    Description: Test
    Value: !Join
      - ""
      - - !Ref AWS::Region
        - !Select
          - 0
          - !Ref PubSubAZList

...