---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # VPC Template
  * For AWS CloudFormation - VPC Template

  ## Resources
  1. VPC
  2. Public/Private Subnet
  3. Public/Private Route & Routing Table
  4. Internet Gateway

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "VPC Configuration"
        Parameters:
          - VpcName
          - VpcCidr
      - 
        Label:
          default: "Subnet Configuration"
        Parameters:
          - PubSubNum
          - PubSubNameList
          - PubSubCidrList
          - PriSubNum
          - PriSubNameList
          - PriSubCidrList

Parameters:
  ProjInfix:
    Description: Infix of Resource Name
    Type: String
    Default: "y2-test"
  VpcName:
    Description: Name of VPC
    Type: String
    Default: "vpc-y2-test"
  VpcCidr:
    Description: CIDR of VPC
    Type: String
    Default: "10.0.0.0/16"
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "
  PubSubNum:
    Description: Number of Public Subnet
    Type: Number
    MaxValue: 6
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "
  PubSubNameList:
    Description: "Name List of Public Subnet"
    Type: String 
  PubSubCidrList:
    Description: "CIDR List of Public Subnet"
    Type: CommaDelimitedList
    AllowedPattern: ""
  PubSubAZList:
    Description: "AZ List of Public Subnet"
    Type: CommaDelimitedList
  PriSubNum:
    Description: Number of Private Subnet
    Type: Number
    MaxValue: 4
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "
  PriSubNameList:
    Description: "Name List of Private Subnet"
    Type: CommaDelimitedList
  PriSubCidrList:
    Description: "CIDR List of Private Subnet"
    Type: CommaDelimitedList
    AllowedPattern: "" 
  PriSubAZList:
    Description: "AZ List of Private Subnet"
    Type: CommaDelimitedList

Conditions:
  IsPubSub1: !Not [!Equals [!Select [0, !Ref PubSubAZList], ""]]
  IsPubSub2: !Not [!Equals [!Select [1, !Ref PubSubAZList], ""]]
  IsPubSub3: !Not [!Equals [!Select [2, !Ref PubSubAZList], ""]]
  IsPubSub4: !Not [!Equals [!Select [3, !Ref PubSubAZList], ""]]

  IsPriSub1: !Not [!Equals [!Select [0, !Ref PriSubNameList], ""]]
  IsPriSub2: !Not [!Equals [!Select [1, !Ref PriSubNameList], ""]]
  IsPriSub3: !Not [!Equals [!Select [2, !Ref PriSubNameList], ""]]
  IsPriSub4: !Not [!Equals [!Select [3, !Ref PriSubNameList], ""]]
  IsPriSub5: !Not [!Equals [!Select [4, !Ref PriSubNameList], ""]]
  IsPriSub6: !Not [!Equals [!Select [5, !Ref PriSubNameList], ""]]

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref VpcName
  PubSub1: 
    Type: 'AWS::EC2::Subnet'
    Condition: IsPubSub1
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [0, !Ref PubSubAZList]
      CidrBlock: !Select [0, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [0, !Ref PubSubNameList]
  PubSub2:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPubSub2
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [1, !Ref PubSubAZList]
      CidrBlock: !Select [1, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [1, !Ref PubSubNameList]
  PubSub3:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPubSub3
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [2, !Ref PubSubAZList]
      CidrBlock: !Select [2, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [2, !Ref PubSubNameList]
  PubSub4:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPubSub4
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [3, !Ref PubSubAZList]
      CidrBlock: !Select [3, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [3, !Ref PubSubNameList]

  PriSub1:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPriSub1
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [0, !Ref PriSubAZList]
      CidrBlock: !Select [0, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [0, !Ref PriSubNameList]
  PriSub2:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPriSub2
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [1, !Ref PriSubAZList]
      CidrBlock: !Select [1, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [1, !Ref PriSubNameList]
  PriSub3:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPriSub3
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [2, !Ref PriSubAZList]
      CidrBlock: !Select [2, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [2, !Ref PriSubNameList]
  PriSub4:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPriSub4
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [3, !Ref PriSubAZList]
      CidrBlock: !Select [3, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [3, !Ref PriSubNameList]
  PriSub5:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPriSub5
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [4, !Ref PriSubAZList]
      CidrBlock: !Select [4, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [4, !Ref PriSubNameList]
  PriSub6:
    Type: 'AWS::EC2::Subnet'
    Condition: IsPriSub6
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - - !Ref 'AWS::Region'
          - !Select [5, !Ref PriSubAZList]
      CidrBlock: !Select [5, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [5, !Ref PriSubNameList]

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Condition: IsPubSub1
    Properties:
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join
            - ''
            - - 'igw-'
              - !Ref NameInfix
  AttachInternetGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Condition: IsPubSub1
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PubRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Condition: IsPubSub1
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: Fn::Join
            - ''
            - - 'rt-'
              - !Ref NameInfix
              - '-pub'
  PubSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPubSub1
    Properties:
      SubnetId: !Ref PubSub1
      RouteTableId: !Ref PubRouteTable
  PubSubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPubSub2
    Properties:
      SubnetId: !Ref PubSub2
      RouteTableId: !Ref PubRouteTable
  PubSubnetRouteTableAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPubSub3
    Properties:
      SubnetId: !Ref PubSub3
      RouteTableId: !Ref PubRouteTable
  PubSubnetRouteTableAssociation4:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPubSub4
    Properties:
      SubnetId: !Ref PubSub4
      RouteTableId: !Ref PubRouteTable
  PubRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway  
  
  PriRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Condition: IsPriSub1
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: Fn::Join
            - ''
            - - 'rt-'
              - !Ref NameInfix
              - '-pri'
  PriSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPriSub1
    Properties:
      SubnetId: !Ref PriSub1
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPriSub2
    Properties:
      SubnetId: !Ref PriSub2
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPriSub3
    Properties:
      SubnetId: !Ref PriSub3
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation4:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPriSub4
    Properties:
      SubnetId: !Ref PriSub4
      RouteTableId: !Ref PriRouteTable 
  PriSubnetRouteTableAssociation5:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPriSub5
    Properties:
      SubnetId: !Ref PriSub5
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation6:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: IsPriSub6
    Properties:
      SubnetId: !Ref PriSub6
      RouteTableId: !Ref PriRouteTable


  TestSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '2073'
          ToPort: '2073'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '40022'
          ToPort: '40022'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: Fn::Join
            - ''
            - - 'sg-'
              - !Ref NameInfix
              - '-default'
...