---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # VPC Template
  * For AWS CloudFormation - VPC Template

  ## Resources
  1. VPC
  2. Public/Private Subnet
  3. Public/Private Route & Routing Table
  4. Internet Gateway

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC Configuration"
        Parameters:
          - VpcName
          - VpcCidr
      - Label:
          default: "Public Subnet Configuration"
        Parameters:
          - PubSubNum
          - PubSubNameList
          - PubSubCidrList
          - PubSubAZList
      - Label:
          default: "Private Subnet Configuration"
        Parameters:
          - PriSubNum
          - PriSubNameList
          - PriSubCidrList
          - PriSubAZList

Parameters:
  ProjInfix:
    Description: Infix of Resource Name
    Type: String
    Default: "y2-test"
  VpcName:
    Description: Name of VPC
    Type: String
    Default: "vpc-y2-test"
  VpcCidr:
    Description: CIDR of VPC
    Type: String
    Default: "10.0.0.0/16"
    AllowedPattern: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$
    ConstraintDescription: "Parameter must only contain "
  PubSubNum:
    Description: Number of Public Subnet
    Type: Number
    Default: 1
    MaxValue: 4
    MinValue: 0
  PubSubNameList:
    Description: "Name List of Public Subnet"
    Type: CommaDelimitedList
    Default: null,sbn-y2-test-pub1,null,null
  PubSubCidrList:
    Description: "CIDR List of Public Subnet"
    Type: CommaDelimitedList
    Default: null,10.0.0.0/24,null,null
  PubSubAZList:
    Description: "AZ List of Public Subnet"
    Type: CommaDelimitedList
    Default: null,a,null,null
  PriSubNum:
    Description: Number of Private Subnet
    Type: Number
    Default: 2
    MaxValue: 6
    MinValue: 0
  PriSubNameList:
    Description: "Name List of Private Subnet"
    Type: CommaDelimitedList
    Default: sbn-y2-test-pri1,null,null,null,sbn-y2-test-pri2,null
  PriSubCidrList:
    Description: "CIDR List of Private Subnet"
    Type: CommaDelimitedList
    Default: 10.0.1.0/24,null,null,null,10.0.2.0/24,null
  PriSubAZList:
    Description: "AZ List of Private Subnet"
    Type: CommaDelimitedList
    Default: a,null,null,null,b,null

Conditions:
  ExistPubSub: !Not [!Equals [0, !Ref PubSubNum]]
  ExistPriSub: !Not [!Equals [0, !Ref PriSubNum]]

  ExistPubSub1: !Not [!Equals [!Select [0, !Ref PubSubAZList], "null"]]
  ExistPubSub2: !Not [!Equals [!Select [1, !Ref PubSubAZList], "null"]]
  ExistPubSub3: !Not [!Equals [!Select [2, !Ref PubSubAZList], "null"]]
  ExistPubSub4: !Not [!Equals [!Select [3, !Ref PubSubAZList], "null"]]
  ExistPriSub1: !Not [!Equals [!Select [0, !Ref PriSubNameList], "null"]]
  ExistPriSub2: !Not [!Equals [!Select [1, !Ref PriSubNameList], "null"]]
  ExistPriSub3: !Not [!Equals [!Select [2, !Ref PriSubNameList], "null"]]
  ExistPriSub4: !Not [!Equals [!Select [3, !Ref PriSubNameList], "null"]]
  ExistPriSub5: !Not [!Equals [!Select [4, !Ref PriSubNameList], "null"]]
  ExistPriSub6: !Not [!Equals [!Select [5, !Ref PriSubNameList], "null"]]


Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref VpcName
  PubSub1: 
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPubSub1
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [0, !Ref PubSubAZList]]]
      CidrBlock: !Select [0, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [0, !Ref PubSubNameList]
  PubSub2: 
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPubSub2
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [1, !Ref PubSubAZList]]]
      CidrBlock: !Select [1, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [1, !Ref PubSubNameList]
  PubSub3: 
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPubSub3
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [2, !Ref PubSubAZList]]]
      CidrBlock: !Select [2, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [2, !Ref PubSubNameList]
  PubSub4: 
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPubSub4
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [3, !Ref PubSubAZList]]]
      CidrBlock: !Select [3, !Ref PubSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [3, !Ref PubSubNameList]

  PriSub1:
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPriSub1
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [0, !Ref PriSubAZList]]]
      CidrBlock: !Select [0, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [0, !Ref PriSubNameList]
  PriSub2:
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPriSub2
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [1, !Ref PriSubAZList]]]
      CidrBlock: !Select [1, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [1, !Ref PriSubNameList]
  PriSub3:
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPriSub3
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [2, !Ref PriSubAZList]]]
      CidrBlock: !Select [2, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [2, !Ref PriSubNameList]
  PriSub4:
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPriSub4
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [3, !Ref PriSubAZList]]]
      CidrBlock: !Select [3, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [3, !Ref PriSubNameList]
  PriSub5:
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPriSub5
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [4, !Ref PriSubAZList]]]
      CidrBlock: !Select [4, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [4, !Ref PriSubNameList]
  PriSub6:
    Type: 'AWS::EC2::Subnet'
    Condition: ExistPriSub6
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', !Select [5, !Ref PriSubAZList]]]
      CidrBlock: !Select [5, !Ref PriSubCidrList]
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Select [5, !Ref PriSubNameList]


  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Condition: ExistPubSub
    Properties:
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join ['', ['igw-', !Ref ProjInfix]]
  AttachInternetGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Condition: ExistPubSub
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway


  PubRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Condition: ExistPubSub
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join ['', ['rt-', !Ref ProjInfix, '-pub']]
  PubSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPubSub1
    Properties:
      SubnetId: !Ref PubSub1
      RouteTableId: !Ref PubRouteTable
  PubSubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPubSub2
    Properties:
      SubnetId: !Ref PubSub2
      RouteTableId: !Ref PubRouteTable
  PubSubnetRouteTableAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPubSub3
    Properties:
      SubnetId: !Ref PubSub3
      RouteTableId: !Ref PubRouteTable
  PubSubnetRouteTableAssociation4:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPubSub4
    Properties:
      SubnetId: !Ref PubSub4
      RouteTableId: !Ref PubRouteTable
  PubRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref PubRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway  
  

  PriRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Condition: ExistPriSub
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join ['', ['rt-', !Ref ProjInfix, '-pri']]
  PriSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPriSub1
    Properties:
      SubnetId: !Ref PriSub1
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPriSub2
    Properties:
      SubnetId: !Ref PriSub2
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPriSub3
    Properties:
      SubnetId: !Ref PriSub3
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation4:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPriSub4
    Properties:
      SubnetId: !Ref PriSub4
      RouteTableId: !Ref PriRouteTable 
  PriSubnetRouteTableAssociation5:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPriSub5
    Properties:
      SubnetId: !Ref PriSub5
      RouteTableId: !Ref PriRouteTable
  PriSubnetRouteTableAssociation6:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: ExistPriSub6
    Properties:
      SubnetId: !Ref PriSub6
      RouteTableId: !Ref PriRouteTable


  TestSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '2073'
          ToPort: '2073'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '40022'
          ToPort: '40022'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join ['', ['sg-', !Ref ProjInfix, '-default']]
...