---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # VPC Template
  * For AWS CloudFormation - VPC Template

  ## Resources
  1. VPC
  2. Public/Private Subnet
  3. Public/Private Route & Routing Table
  4. Internet Gateway

  ## 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "VPC Configuration"
        Parameters:
          - VpcName
          - VpcCidr
      - 
        Label:
          default: "Subnet Configuration"
        Parameters:
          - PubSubNum
          - PubSubNameList
          - PubSubCidrList
          - PriSubNum
          - PriSubNameList
          - PriSubCidrList
Mappings:


Parameters:
  VpcName:
    Description: Name of VPC
    Type: String
    Default: "vpc-y2-test"
  VpcCidr:
    Description: CIDR of VPC
    Type: String
    Default: "10.0.0.0/16"
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "
  PubSubNum:
    Description: Number of Public Subnet
    Type: Number
    AllowedPattern: ""
    ConstraintDescription: ""
  PubSubNameList:
    Description: "Name List of Public Subnet"
    Type: String 
  PubSubCidrList:
    Description: "CIDR List of Public Subnet"
    Type: CommaDelimitedList
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "
  PubSubAZList:
    Description: "AZ List of Public Subnet"
    Type: CommaDelimitedList
  PriSubNum:
    Description: Number of Private Subnet
    Type: Number
    AllowedPattern: ""
    ConstraintDescription: 
  PriSubNameList:
    Description: "Name List of Private Subnet"
    Type: CommaDelimitedList
  PriSubCidrList:
    Description: "CIDR List of Private Subnet"
    Type: CommaDelimitedList
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "  
  PriSubAZList:
    Description: "AZ List of Private Subnet"
    Type: CommaDelimitedList

Rules:



Conditions:




Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: {{ VpcCidr }}
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: {{ VpcName }}
  PubSub1: 
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: Fn::Join
        - ''
        - !Ref 'AWS::Region'
        - !If [!Ref {{ PubSubAZList[0] }}, !Ref {{ PubSubAZList[0] }}, !Ref 'AWS::NoValue']
      CidrBlock: !Ref {{ PubSubCidrList[0] }}
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: 'y2-sbn-test'
  PubSub2:
  PubSub3:
  PubSub4:

  PriSub1:
  PriSub2:
  PriSub3:
  PriSub4:
  PriSub5:
  PriSub6:


  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-west-1a"
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: 'y2-sbn-test'
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: 'y2-igw-test'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: 'y2-rt-test'
  Route:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '2073'
          ToPort: '2073'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '40022'
          ToPort: '40022'
          CidrIp: 0.0.0.0/0
...