---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template VPC_Single_Instance_In_Subnet: Sample
  template showing how to create a VPC and add an EC2 instance with an Elastic
  IP address and a security group. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS resources used if you create a
  stack from this template.
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: "us-west-2a"
      # SubnetId: !Ref Subnet
      ImageId: "ami-0e0f72498373d693d"
      InstanceType: "t2.medium"
      #Volumes: 
      #  - Device: ''
      #    VolumeId: ''
      EbsOptimized: false
      BlockDeviceMappings:
        # Root Volume
        - DeviceName: '/dev/xvda'
          Ebs:
            # SnapshotId: 'snap-01b10d61649e94224'
            VolumeSize: 8
            VolumeType: 'gp2'
            # Iops: 1000
            Encrypted: false
            # KmsKeyId: arn:...
            DeleteOnTermination: true
      # IamInstanceProfile: IAM Name
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: 'terminate'
      # KeyName: String
      Monitoring: false
      # Tenancy: 'default'    # dedicated / default / host
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: 'Primary network interface'
          DeviceIndex: '0'
          # Ipv6AddressCount: Integer
          # Ipv6Addresses: 
          #  - InstanceIpv6Address
          # NetworkInterfaceId: String
          # PrivateIpAddress: String
          GroupSet:
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref Subnet
      # SecurityGroupIds:
      #  - !Ref InstanceSecurityGroup
      # SecurityGroups: 
      #  - String
      # SourceDestCheck: Boolean
      UserData:
        Fn::Base64:
          !Sub |
            <powershell>
            net user Administrator “koreanre12!”
            $port = 2073
            Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-TCP' -name "PortNumber" -Value $port
            New-NetFirewallRule -DisplayName 'RDPPORTLatest' -Direction Inbound -Action Allow -Protocol TCP -LocalPort $port
            Restart-Service termservice -Force
            </powershell>
      Tags:
        - Key: 'Name'
          Value: 'TestWindows'
...