---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Application Load Balancer Template
  * For AWS CloudFormation - Application Load Balancer Template
  * You must create alb, after create 'Target Group'.


  ## Resources
  1. ElasticLoadBalancingV2::LoadBalancer

  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Load Balancer Configuration"
        Parameters:
          - LBTypeParam
          - LBNameParam
      - Label:
          default: "Network Configuration"
        Parameters:
          - SchemeParam
          - IpAddressTypeParam
          - SubnetListParam
          - SecurityGroupListParam


Mappings:
  AttrMap:
    application:
      deletionProtection_enabled: true
      accessLogs_s3_enabled: false
      accessLogs_s3_bucket: ""
      accessLogs_s3_prefix: ""
      ipv6_denyAllIgwTraffic: false           # internet-facing : false / # internal : true
      idleIimeout_timeoutSeconds: 60          # 1~4000
      routing_http_desyncMitigationMode: "defensive"  # Default defensive / monitor / strictest
      routing_http_dropInvalidHeaderFields_enabled: false            # Default false / true
      routing_http_xAmznTlsVersionAndCipherSuite_enabled: false   # Default false / true
      routing_http_xffClientPort_enabled: false   # Default false / true
      routing_http2_enabled: true     # Default true / false
      waf_failOpen_enabled: false    # Default false / true
    network:
      deletionProtection_enabled: true 
      accessLogs_s3_enabled: false
      accessLogs_s3_bucket: ""
      accessLogs_s3_prefix: ""
      ipv6_denyAllIgwTraffic: false             # internet-facing : false / # internal : true
      loadBalancing_crossZone_enabled: false    # Default false / true


Parameters:
  LBTypeParam:
    Description: 'Load Balancer Type'
    Type: String
    Default: 'application'
    AllowedValues:
      - 'application'
      - 'gateway'
      - 'network'
  LBNameParam:
    Description: 'Load Balancer Name (Maximun: 32)'
    Type: String
    MaxLength: 32
    MinLength: 1
    AllowedPattern: "^(?!internal-)[0-9a-zA-Z-]{1,32}$"

  SchemeParam:
    Description: 'Load Balancer Scheme : internet-facing / internal'
    Type: String
    Default: 'internal'
    AllowedValues:
      - 'internet-facing'
      - 'internal'
  IpAddressTypeParam:
    Description: 'IP Address Type : dualstack / ipv4'
    Type: String
    Default: 'ipv4'
    AllowedValues:
      - 'dualstack'
      - 'ipv4'
  SubnetListParam:
    Description: 'Subnet List'
    Type: CommaDelimitedList
    # subnet-0b9f3f5f42213970e,subnet-0aa8348952ce73b14
  SecurityGroupListParam:
    Description: 'Security Group List'
    Type: CommaDelimitedList
    # sg-05b5cd25857dcb617

#Rules:


#Conditions:
#  IsPubSub1: !Not [!Equals [!Select [0, !Ref PubSubAZList], ""]]


Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      # Basic Configuration
      Type: !Ref LBTypeParam
      Name: !Ref LBNameParam
      Scheme: !Ref SchemeParam
      IpAddressType: !Ref IpAddressTypeParam


      # Network Configuration
      #SubnetMappings: 
      #  - SubnetMapping
      Subnets: !Ref SubnetListParam
      SecurityGroups: !Ref SecurityGroupListParam

      LoadBalancerAttributes:
        # All LB
        - Key: "deletion_protection.enabled"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, deletionProtection_enabled]

        # Application LB and Network LB
        - Key: "access_logs.s3.enabled"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, accessLogs_s3_enabled]
#        - Key: "access_logs.s3.bucket"
#          Value: !FindInMap [AttrMap, !Ref LBTypeParam, accessLogs_s3_bucket]
#        - Key: "access_logs.s3.prefix"
#          Value: !FindInMap [AttrMap, !Ref LBTypeParam, accessLogs_s3_prefix]
#        - Key: "ipv6.deny_all_igw_traffic"
#          Value: !FindInMap [AttrMap, !Ref LBTypeParam, ipv6_denyAllIgwTraffic]

        # Only Application LB
        - Key: "idle_timeout.timeout_seconds"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, idleIimeout_timeoutSeconds]
        - Key: "routing.http.desync_mitigation_mode"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, routing_http_desyncMitigationMode]
        - Key: "routing.http.drop_invalid_header_fields.enabled"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, routing_http_dropInvalidHeaderFields_enabled]
        - Key: "routing.http.x_amzn_tls_version_and_cipher_suite.enabled"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, routing_http_xAmznTlsVersionAndCipherSuite_enabled]
        - Key: "routing.http.xff_client_port.enabled"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, routing_http_xffClientPort_enabled]
        - Key: "routing.http2.enabled"
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, routing_http2_enabled]
        - Key: "waf.fail_open.enabled "
          Value: !FindInMap [AttrMap, !Ref LBTypeParam, waf_failOpen_enabled]
        # Network LB and Gateway LB
#        - Key: "load_balancing.cross_zone.enabled"
#          Value: !FindInMap [AttrMap, !Ref LBTypeParam, loadBalancing_crossZone_enabled]

      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref LBNameParam
      


Outputs:
  LoadBalancerId:
    Description: LoadBalancer ID
    Value: !Ref LoadBalancer
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerId"
...