---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  # Application Load Balancer Template
  * For AWS CloudFormation - Application Load Balancer Template
  * You must create alb, after create 'Target Group'.


  ## Resources
  1. ElasticLoadBalancingV2::LoadBalancer
  2. ElasticLoadBalancingV2::Listener
  3. ElasticLoadBalancingV2::ListenerRule
  * ElasticLoadBalancingV2::ListenerCertificate : X


  ## Parameter


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC Configuration"
        Parameters:
          - VpcName
          - VpcCidr
      - Label:
          default: "Subnet Configuration"
        Parameters:
          - PubSubNum
          - PubSubNameList
          - PubSubCidrList
          - PriSubNum
          - PriSubNameList
          - PriSubCidrList
Mappings:
  DBEngineMap:
    mariadb:
      Log:
        - audit
        - error
        - general
        - slowquery

Parameters:
  ProjInfix:
    Description: Infix of Resource Name
    Type: String
    Default: "y2-test"
  VpcName:
    Description: Name of VPC
    Type: String
    Default: "vpc-y2-test"
  VpcCidr:
    Description: CIDR of VPC
    Type: String
    Default: "10.0.0.0/16"
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "
  PubSubNum:
    Description: Number of Public Subnet
    Type: Number
    AllowedPattern: ""
    ConstraintDescription: "Parameter must only contain "
  PubSubNameList:
    Description: "Name List of Public Subnet"
    Type: String 
  PubSubCidrList:
    Description: "CIDR List of Public Subnet"
    Type: CommaDelimitedList
    AllowedPattern: ""
  PubSubAZList:
    Description: "AZ List of Public Subnet"
    Type: CommaDelimitedList

Rules:



Conditions:
  IsPubSub1: !Not [!Equals [!Select [0, !Ref PubSubAZList], ""]]

Resources:

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      # Basic Configuration
      Type: !Ref LBTypeParam
      Name: !Ref LBNameParam
      Scheme: !Ref SchemeParam
      IpAddressType: !Ref IpAddressTypeParam


      # Network Configuration
      #SubnetMappings: 
      #  - SubnetMapping
      Subnets: 
        - !Ref SubnetListParam
      SecurityGroups: 
        - !Ref SecurityGroupLIstParam


      LoadBalancerAttributes:
        # All LB
        - Key: "deletion_protection.enabled"
          Value: false  # true

        # Application LB and Network LB
#        - Key: "access_logs.s3.enabled"
#          Value: 
#        - Key: "access_logs.s3.bucket"
#          Value: 
#        - Key: "access_logs.s3.prefix"
#          Value: 
#        - Key: "ipv6.deny_all_igw_traffic"
#          Value: 
        # Only Application LB
#        - Key: "idle_timeout.timeout_seconds"
#          Value: 
#        - Key: "routing.http.desync_mitigation_mode"
#          Value: 
#        - Key: "routing.http.drop_invalid_header_fields.enabled"
#          Value: 
#        - Key: "routing.http.x_amzn_tls_version_and_cipher_suite.enabled"
#          Value: 
#        - Key: "routing.http.xff_client_port.enabled"
#          Value: 
#        - Key: "routing.http2.enabled"
#          Value: 
#        - Key: "waf.fail_open.enabled "
#          Value: 
        # Network LB and Gateway LB
#        - Key: "load_balancing.cross_zone.enabled"
#          Value: 

          
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref LBNameParam
      


  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      AlpnPolicy: 
        - String
      Certificates: 
        - Certificate
      DefaultActions: 
        - Action
      LoadBalancerArn: String
      Port: Integer
      Protocol: String
      SslPolicy: String



  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - Action
      Conditions: 
        - RuleCondition
      ListenerArn: String
      Priority: Integer









 
      Tags:
        - Key: CloudFormationStack
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: Fn::Join
            - ''
            - - 'sg-'
              - !Ref NameInfix
              - '-default'



Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref EC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"
...